/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRMS_Interface;

import HMS_Database.MyDBConnection;
import HMS_Home.HMS_Methods;
import HMS_Home.MHome;
import HRMS_Codes.HR_Methods;
import HRMS_Codes.Hotel;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class UserManagement extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Hotel c = new Hotel();
    HR_Methods hrm = new HR_Methods();

    public UserManagement() {
        initComponents();
        //conn = (Connection) MyDBConnection.Myconnect();
        HMS_Methods hm = new HMS_Methods();
        hm.unmovableInternal(this);
        //hrm.LoadEmployeeTableToForm(txt_empID, txt_fname, txt_initialName, txt_gender, txt_nic, txt_dob, txtA_address, txt_hno, txt_mno, txt_mail, dc_startdate, txt_dptn, txt_dsgn, txt_usrnme, pwd_password);

    }

    public void LoadTable() throws SQLException {

        try {

            String sql = "select * from userlog";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnl_addUpdateEmp = new javax.swing.JPanel();
        lbl_mno1 = new javax.swing.JLabel();
        txt_usrnme = new javax.swing.JTextField();
        lbl_hno1 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        lbl_employeeID = new javax.swing.JLabel();
        lbl_fname = new javax.swing.JLabel();
        txt_empID = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        lbl_initialName = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JLabel();
        txt_initialName = new javax.swing.JTextField();
        lbl_dob = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        jScrollPaneAddress = new javax.swing.JScrollPane();
        txtA_address = new javax.swing.JTextArea();
        lbl_hno = new javax.swing.JLabel();
        txt_dptn = new javax.swing.JTextField();
        txt_dsgn = new javax.swing.JTextField();
        lbl_mno = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        txt_mno = new javax.swing.JTextField();
        lbl_designation = new javax.swing.JLabel();
        lbl_startdate = new javax.swing.JLabel();
        lbl_department = new javax.swing.JLabel();
        txt_hno = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        pwd_password = new javax.swing.JPasswordField();
        txt_gender = new javax.swing.JTextField();
        dc_startdate = new com.toedter.calendar.JDateChooser();
        lbl_eid = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_border = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_border1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_SearchValidate = new javax.swing.JLabel();
        emp_background = new javax.swing.JLabel();
        PnlMenu = new javax.swing.JPanel();
        btn_jobMain = new javax.swing.JButton();
        btn_UserMain = new javax.swing.JButton();
        btn_attendeceMain = new javax.swing.JButton();
        btn_EmployeeMain = new javax.swing.JButton();
        btn_payrollMain = new javax.swing.JButton();
        btn_interviewMain = new javax.swing.JButton();

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MenuBar_Back_Main_HR.jpg"))); // NOI18N
        jLabel17.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel17.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel17.setPreferredSize(new java.awt.Dimension(1190, 75));

        setTitle("User Management");
        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_addUpdateEmp.setBackground(new java.awt.Color(247, 249, 255));
        pnl_addUpdateEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_addUpdateEmp.setForeground(new java.awt.Color(240, 240, 240));
        pnl_addUpdateEmp.setPreferredSize(new java.awt.Dimension(1140, 460));
        pnl_addUpdateEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_mno1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_mno1.setText("Password            :");
        lbl_mno1.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_addUpdateEmp.add(lbl_mno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 100, 30));

        txt_usrnme.setEditable(false);
        txt_usrnme.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_usrnme, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, -1, -1));

        lbl_hno1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_hno1.setText("User Name         :");
        lbl_hno1.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_addUpdateEmp.add(lbl_hno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 100, 30));

        txt_mail.setEditable(false);
        txt_mail.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        lbl_employeeID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_employeeID.setText("Employee ID          :");
        lbl_employeeID.setPreferredSize(new java.awt.Dimension(110, 30));
        pnl_addUpdateEmp.add(lbl_employeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 30));

        lbl_fname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_fname.setText("Full Name               :");
        lbl_fname.setPreferredSize(new java.awt.Dimension(110, 30));
        pnl_addUpdateEmp.add(lbl_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, 30));

        txt_empID.setEditable(false);
        txt_empID.setPreferredSize(new java.awt.Dimension(210, 30));
        txt_empID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empIDActionPerformed(evt);
            }
        });
        pnl_addUpdateEmp.add(txt_empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 210, 30));

        txt_fname.setEditable(false);
        txt_fname.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 30));

        lbl_initialName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_initialName.setText("Name with Initial  :");
        lbl_initialName.setPreferredSize(new java.awt.Dimension(110, 30));
        pnl_addUpdateEmp.add(lbl_initialName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 30));

        lbl_nic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_nic.setText("NIC                           :");
        lbl_nic.setPreferredSize(new java.awt.Dimension(110, 30));
        pnl_addUpdateEmp.add(lbl_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, 30));

        txt_initialName.setEditable(false);
        txt_initialName.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_initialName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 210, 30));

        lbl_dob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_dob.setText("Birth Day                :");
        lbl_dob.setPreferredSize(new java.awt.Dimension(110, 30));
        pnl_addUpdateEmp.add(lbl_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 110, 30));

        lbl_address.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_address.setText("Address               :");
        lbl_address.setPreferredSize(new java.awt.Dimension(100, 140));
        pnl_addUpdateEmp.add(lbl_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 100, 140));

        jScrollPaneAddress.setPreferredSize(new java.awt.Dimension(210, 140));

        txtA_address.setEditable(false);
        txtA_address.setColumns(20);
        txtA_address.setRows(5);
        txtA_address.setPreferredSize(new java.awt.Dimension(210, 140));
        jScrollPaneAddress.setViewportView(txtA_address);

        pnl_addUpdateEmp.add(jScrollPaneAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        lbl_hno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_hno.setText("Home Number    :");
        lbl_hno.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_addUpdateEmp.add(lbl_hno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, 30));

        txt_dptn.setEditable(false);
        txt_dptn.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_dptn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, -1, -1));

        txt_dsgn.setEditable(false);
        txt_dsgn.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_dsgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        lbl_mno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_mno.setText("Mobile Number   :");
        lbl_mno.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_addUpdateEmp.add(lbl_mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 100, 30));

        lbl_mail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_mail.setText("Email                     :");
        lbl_mail.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_addUpdateEmp.add(lbl_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 100, 30));

        txt_nic.setEditable(false);
        txt_nic.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 210, 30));

        txt_mno.setEditable(false);
        txt_mno.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        lbl_designation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_designation.setText("Designation        :");
        lbl_designation.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_addUpdateEmp.add(lbl_designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 100, 30));

        lbl_startdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_startdate.setText("Strat Date          :");
        lbl_startdate.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_addUpdateEmp.add(lbl_startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 100, 30));

        lbl_department.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_department.setText("Department        :");
        lbl_department.setToolTipText("");
        lbl_department.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_addUpdateEmp.add(lbl_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 100, 30));

        txt_hno.setEditable(false);
        txt_hno.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_addUpdateEmp.add(txt_hno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        txt_dob.setEditable(false);
        pnl_addUpdateEmp.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 210, 30));

        pwd_password.setEditable(false);
        pnl_addUpdateEmp.add(pwd_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 210, 30));

        txt_gender.setEditable(false);
        pnl_addUpdateEmp.add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 210, 30));

        dc_startdate.setDateFormatString("yyyy-MM-dd");
        dc_startdate.setEnabled(false);
        dc_startdate.setPreferredSize(new java.awt.Dimension(210, 30));
        dc_startdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dc_startdateKeyTyped(evt);
            }
        });
        pnl_addUpdateEmp.add(dc_startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, -1, -1));
        pnl_addUpdateEmp.add(lbl_eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 210, 20));

        lbl_gender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_gender.setText("Gender                   :");
        lbl_gender.setPreferredSize(new java.awt.Dimension(110, 30));
        pnl_addUpdateEmp.add(lbl_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 110, 30));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder("User Login Details"));
        pnl_addUpdateEmp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 340, 140));

        lbl_border.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Details"));
        lbl_border.setPreferredSize(new java.awt.Dimension(1120, 370));
        pnl_addUpdateEmp.add(lbl_border, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 360, 380));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Employment Details"));
        pnl_addUpdateEmp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 340, 210));

        lbl_border1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Details"));
        lbl_border1.setPreferredSize(new java.awt.Dimension(1120, 370));
        pnl_addUpdateEmp.add(lbl_border1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 380, 380));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome");
        pnl_addUpdateEmp.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 50));
        pnl_addUpdateEmp.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 180, 50));

        jPanel1.add(pnl_addUpdateEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 174, 239));
        jButton5.setText("Home");
        jButton5.setBorder(null);
        jButton5.setPreferredSize(new java.awt.Dimension(110, 25));
        jButton5.setSelected(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 50));

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(0, 174, 239));
        btn_edit.setText("Edit");
        btn_edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 3));
        btn_edit.setPreferredSize(new java.awt.Dimension(70, 30));
        btn_edit.setSelected(true);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 110, 40));

        btn_add.setBackground(new java.awt.Color(255, 255, 255));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add.setForeground(new java.awt.Color(0, 174, 239));
        btn_add.setText("Save");
        btn_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 3));
        btn_add.setEnabled(false);
        btn_add.setPreferredSize(new java.awt.Dimension(70, 30));
        btn_add.setSelected(true);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 110, 40));

        btn_reset.setBackground(new java.awt.Color(255, 255, 255));
        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(0, 174, 239));
        btn_reset.setText("Cancel");
        btn_reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 3));
        btn_reset.setEnabled(false);
        btn_reset.setPreferredSize(new java.awt.Dimension(70, 30));
        btn_reset.setSelected(true);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 520, 110, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 174, 239));
        jButton4.setText("Logout");
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.setPreferredSize(new java.awt.Dimension(110, 25));
        jButton4.setSelected(true);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, -1, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 1190, 10));

        lbl_SearchValidate.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lbl_SearchValidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 390, 20));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel1.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_jobMain.setBackground(new java.awt.Color(153, 204, 255));
        btn_jobMain.setForeground(new java.awt.Color(255, 255, 255));
        btn_jobMain.setText("Job Analysis");
        btn_jobMain.setBorder(null);
        btn_jobMain.setContentAreaFilled(false);
        btn_jobMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_jobMain.setOpaque(true);
        btn_jobMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jobMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_jobMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_jobMainMouseExited(evt);
            }
        });
        btn_jobMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jobMainActionPerformed(evt);
            }
        });
        PnlMenu.add(btn_jobMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 190, 30));

        btn_UserMain.setBackground(new java.awt.Color(0, 174, 238));
        btn_UserMain.setForeground(new java.awt.Color(255, 255, 255));
        btn_UserMain.setText("User");
        btn_UserMain.setBorder(null);
        btn_UserMain.setContentAreaFilled(false);
        btn_UserMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_UserMain.setOpaque(true);
        btn_UserMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UserMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UserMainMouseExited(evt);
            }
        });
        btn_UserMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UserMainActionPerformed(evt);
            }
        });
        PnlMenu.add(btn_UserMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 30));

        btn_attendeceMain.setBackground(new java.awt.Color(153, 204, 255));
        btn_attendeceMain.setForeground(new java.awt.Color(255, 255, 255));
        btn_attendeceMain.setText("Attendence");
        btn_attendeceMain.setBorder(null);
        btn_attendeceMain.setContentAreaFilled(false);
        btn_attendeceMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_attendeceMain.setOpaque(true);
        btn_attendeceMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_attendeceMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_attendeceMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_attendeceMainMouseExited(evt);
            }
        });
        btn_attendeceMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attendeceMainActionPerformed(evt);
            }
        });
        PnlMenu.add(btn_attendeceMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 190, 30));

        btn_EmployeeMain.setBackground(new java.awt.Color(153, 204, 255));
        btn_EmployeeMain.setForeground(new java.awt.Color(255, 255, 255));
        btn_EmployeeMain.setText("Employee");
        btn_EmployeeMain.setBorder(null);
        btn_EmployeeMain.setContentAreaFilled(false);
        btn_EmployeeMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_EmployeeMain.setOpaque(true);
        btn_EmployeeMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EmployeeMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EmployeeMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmployeeMainMouseExited(evt);
            }
        });
        btn_EmployeeMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeMainActionPerformed(evt);
            }
        });
        PnlMenu.add(btn_EmployeeMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 190, 30));

        btn_payrollMain.setBackground(new java.awt.Color(153, 204, 255));
        btn_payrollMain.setForeground(new java.awt.Color(255, 255, 255));
        btn_payrollMain.setText("Payroll");
        btn_payrollMain.setBorder(null);
        btn_payrollMain.setContentAreaFilled(false);
        btn_payrollMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_payrollMain.setOpaque(true);
        btn_payrollMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_payrollMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_payrollMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_payrollMainMouseExited(evt);
            }
        });
        btn_payrollMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payrollMainActionPerformed(evt);
            }
        });
        PnlMenu.add(btn_payrollMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 190, 30));

        btn_interviewMain.setBackground(new java.awt.Color(153, 204, 255));
        btn_interviewMain.setForeground(new java.awt.Color(255, 255, 255));
        btn_interviewMain.setText("Interview & Candidate");
        btn_interviewMain.setBorder(null);
        btn_interviewMain.setContentAreaFilled(false);
        btn_interviewMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_interviewMain.setOpaque(true);
        btn_interviewMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_interviewMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_interviewMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_interviewMainMouseExited(evt);
            }
        });
        btn_interviewMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_interviewMainActionPerformed(evt);
            }
        });
        PnlMenu.add(btn_interviewMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, 30));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        Color blueColor = new Color(0, 174, 239);
        jButton4.setBackground(blueColor);
        jButton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        Color grColor = new Color(240, 240, 240);
        Color blueColor = new Color(0, 174, 239);
        jButton4.setBackground(grColor);
        jButton4.setForeground(blueColor);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure you want to Logout?", "Logout Confirmation", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons, ObjButtons[1]);
        if (PromptResult == JOptionPane.YES_OPTION) {
            MainLogin lg = new MainLogin();
            JDesktopPane desktopPane = getDesktopPane();
            desktopPane.add(lg).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_empIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empIDActionPerformed

    }//GEN-LAST:event_txt_empIDActionPerformed

    private void dc_startdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dc_startdateKeyTyped

    }//GEN-LAST:event_dc_startdateKeyTyped

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            boolean status = HR_Methods.UpdateEmployeeInDB(txt_empID.getText(), txt_fname.getText(), txt_initialName.getText(),
                    txtA_address.getText(), txt_hno.getText(), txt_mno.getText(), txt_mail.getText(), txt_usrnme.getText(),
                    pwd_password.getText());
            if (status = true) {
                JOptionPane.showMessageDialog(null, "employee Record Update Successfully");
                txtA_address.setEditable(false);
                txt_fname.setEditable(false);
                txt_hno.setEditable(false);
                txt_initialName.setEditable(false);
                txt_mail.setEditable(false);
                txt_mno.setEditable(false);
                txt_usrnme.setEditable(false);
                pwd_password.setEditable(false);
                btn_add.setEnabled(false);
                btn_reset.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "employee Record cant update");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Can't save record..Check fields and try again");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // emptyForm();
        txtA_address.setEditable(false);
        txt_fname.setEditable(false);
        txt_hno.setEditable(false);
        txt_initialName.setEditable(false);
        txt_mail.setEditable(false);
        txt_mno.setEditable(false);
        txt_usrnme.setEditable(false);
        pwd_password.setEditable(false);
        btn_add.setEnabled(false);
        btn_reset.setEnabled(false);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_jobMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jobMainMouseEntered
        // TODO add your handling code here:
        Color blueColor = new Color(0, 174, 239);
        btn_jobMain.setBackground(blueColor);
        btn_jobMain.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_jobMainMouseEntered

    private void btn_jobMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jobMainMouseExited
        // TODO add your handling code here:
        Color whColor = new Color(255, 255, 255);
        Color blueColor = new Color(0, 174, 239);
        btn_jobMain.setBackground(whColor);
        btn_jobMain.setForeground(blueColor);
    }//GEN-LAST:event_btn_jobMainMouseExited

    private void btn_jobMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jobMainActionPerformed
        // TODO add your handling code here:
        JobAnalysis ja = new JobAnalysis();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(ja).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_jobMainActionPerformed

    private void btn_UserMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UserMainMouseEntered
        // TODO add your handling code here:
        Color blueColor = new Color(0, 174, 239);
        btn_UserMain.setBackground(blueColor);
        btn_UserMain.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_UserMainMouseEntered

    private void btn_UserMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UserMainMouseExited
        // TODO add your handling code here:
        Color whColor = new Color(255, 255, 255);
        Color blueColor = new Color(0, 174, 239);
        btn_UserMain.setBackground(whColor);
        btn_UserMain.setForeground(blueColor);
    }//GEN-LAST:event_btn_UserMainMouseExited

    private void btn_UserMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UserMainActionPerformed
        // TODO add your handling code here:
        UserManagement um = new UserManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(um).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_UserMainActionPerformed

    private void btn_attendeceMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attendeceMainMouseEntered
        // TODO add your handling code here:
        Color blueColor = new Color(0, 174, 239);
        btn_attendeceMain.setBackground(blueColor);
        btn_attendeceMain.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_attendeceMainMouseEntered

    private void btn_attendeceMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attendeceMainMouseExited
        // TODO add your handling code here:
        Color whColor = new Color(255, 255, 255);
        Color blueColor = new Color(0, 174, 239);
        btn_attendeceMain.setBackground(whColor);
        btn_attendeceMain.setForeground(blueColor);
    }//GEN-LAST:event_btn_attendeceMainMouseExited

    private void btn_attendeceMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attendeceMainActionPerformed
        // TODO add your handling code here:
        AttendanceManagement am = new AttendanceManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(am).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_attendeceMainActionPerformed

    private void btn_EmployeeMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmployeeMainMouseEntered
        // TODO add your handling code here:
        Color blueColor = new Color(0, 174, 239);
        btn_EmployeeMain.setBackground(blueColor);
        btn_EmployeeMain.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_EmployeeMainMouseEntered

    private void btn_EmployeeMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmployeeMainMouseExited
        // TODO add your handling code here:
        Color whColor = new Color(255, 255, 255);
        Color blueColor = new Color(0, 174, 239);
        btn_EmployeeMain.setBackground(whColor);
        btn_EmployeeMain.setForeground(blueColor);
    }//GEN-LAST:event_btn_EmployeeMainMouseExited

    private void btn_EmployeeMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeMainActionPerformed
        // TODO add your handling code here:
        EmployeeManagement em = new EmployeeManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(em).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EmployeeMainActionPerformed

    private void btn_payrollMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_payrollMainMouseEntered
        // TODO add your handling code here:
        Color blueColor = new Color(0, 174, 239);
        btn_payrollMain.setBackground(blueColor);
        btn_payrollMain.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_payrollMainMouseEntered

    private void btn_payrollMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_payrollMainMouseExited
        // TODO add your handling code here:
        Color whColor = new Color(255, 255, 255);
        Color blueColor = new Color(0, 174, 239);
        btn_payrollMain.setBackground(whColor);
        btn_payrollMain.setForeground(blueColor);
    }//GEN-LAST:event_btn_payrollMainMouseExited

    private void btn_payrollMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payrollMainActionPerformed
        // TODO add your handling code here:
        Payroll pr = new Payroll();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(pr).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_payrollMainActionPerformed

    private void btn_interviewMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_interviewMainMouseEntered
        // TODO add your handling code here:
        Color blueColor = new Color(0, 174, 239);
        btn_interviewMain.setBackground(blueColor);
        btn_interviewMain.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_interviewMainMouseEntered

    private void btn_interviewMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_interviewMainMouseExited
        // TODO add your handling code here:
        Color whColor = new Color(255, 255, 255);
        Color blueColor = new Color(0, 174, 239);
        btn_interviewMain.setBackground(whColor);
        btn_interviewMain.setForeground(blueColor);
    }//GEN-LAST:event_btn_interviewMainMouseExited

    private void btn_interviewMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_interviewMainActionPerformed
        // TODO add your handling code here:
        InterviewManagement im = new InterviewManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(im).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_interviewMainActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        txtA_address.setEditable(true);
        txt_fname.setEditable(true);
        txt_hno.setEditable(true);
        txt_initialName.setEditable(true);
        txt_mail.setEditable(true);
        txt_mno.setEditable(true);
        txt_usrnme.setEditable(true);
        pwd_password.setEditable(true);
        btn_add.setEnabled(true);
        btn_reset.setEnabled(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_interviewMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_interviewMainMouseClicked
        // TODO add your handling code here:
         InterviewManagement im = new InterviewManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(im).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_interviewMainMouseClicked

    private void btn_EmployeeMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmployeeMainMouseClicked
        // TODO add your handling code here:
        EmployeeManagement em = new EmployeeManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(em).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EmployeeMainMouseClicked

    private void btn_attendeceMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attendeceMainMouseClicked
        // TODO add your handling code here:
         AttendanceManagement am = new AttendanceManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(am).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_attendeceMainMouseClicked

    private void btn_payrollMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_payrollMainMouseClicked
        // TODO add your handling code here:
         Payroll pr = new Payroll();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(pr).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_payrollMainMouseClicked

    private void btn_jobMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jobMainMouseClicked
        // TODO add your handling code here:
        JobAnalysis ja = new JobAnalysis();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(ja).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_jobMainMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        MHome mh = new MHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(mh).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    public javax.swing.JButton btn_EmployeeMain;
    public javax.swing.JButton btn_UserMain;
    private javax.swing.JButton btn_add;
    public javax.swing.JButton btn_attendeceMain;
    private javax.swing.JButton btn_edit;
    public javax.swing.JButton btn_interviewMain;
    public javax.swing.JButton btn_jobMain;
    public javax.swing.JButton btn_payrollMain;
    private javax.swing.JButton btn_reset;
    public com.toedter.calendar.JDateChooser dc_startdate;
    private javax.swing.JLabel emp_background;
    private javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneAddress;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_SearchValidate;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_border;
    private javax.swing.JLabel lbl_border1;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_designation;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_eid;
    private javax.swing.JLabel lbl_employeeID;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_hno;
    private javax.swing.JLabel lbl_hno1;
    private javax.swing.JLabel lbl_initialName;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_mno;
    private javax.swing.JLabel lbl_mno1;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_startdate;
    private javax.swing.JPanel pnl_addUpdateEmp;
    public javax.swing.JPasswordField pwd_password;
    public javax.swing.JTextArea txtA_address;
    public javax.swing.JTextField txt_dob;
    public javax.swing.JTextField txt_dptn;
    public javax.swing.JTextField txt_dsgn;
    public javax.swing.JTextField txt_empID;
    public javax.swing.JTextField txt_fname;
    public javax.swing.JTextField txt_gender;
    public javax.swing.JTextField txt_hno;
    public javax.swing.JTextField txt_initialName;
    public javax.swing.JTextField txt_mail;
    public javax.swing.JTextField txt_mno;
    public javax.swing.JTextField txt_nic;
    public javax.swing.JTextField txt_usrnme;
    // End of variables declaration//GEN-END:variables
}
