/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import CustomerManagement.CustomerManagementWindow;
import FinanceManagement.FinanceManagementWindow;
import HRManagement.HRManagementWindow;
import StockManagement.StockManagementWindow;

/**
 *
 * @author Isira
 */
public class MainWindow extends javax.swing.JFrame {

    private static MainWindow instance;
    private static Object monitor = new Object();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    public static MainWindow getInstance() {
        synchronized(monitor) {
            if(instance == null)
                instance = new MainWindow();
        }
        return instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCusManagement = new javax.swing.JButton();
        btnFinManagement = new javax.swing.JButton();
        btnHRManagement = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnStockManagement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Window");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStockManagementMouseClicked(evt);
            }
        });

        btnCusManagement.setBackground(new java.awt.Color(255, 102, 102));
        btnCusManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCusManagement.setText("Customer Management");
        btnCusManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCusManagementMouseClicked(evt);
            }
        });

        btnFinManagement.setBackground(new java.awt.Color(204, 153, 0));
        btnFinManagement.setText("Finance Management");
        btnFinManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinManagementMouseClicked(evt);
            }
        });

        btnHRManagement.setBackground(new java.awt.Color(51, 255, 51));
        btnHRManagement.setText("HR Management");
        btnHRManagement.setOpaque(false);
        btnHRManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHRManagementMouseClicked(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        btnStockManagement.setBackground(new java.awt.Color(51, 0, 153));
        btnStockManagement.setForeground(new java.awt.Color(238, 238, 238));
        btnStockManagement.setText("Stock Management");
        btnStockManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStockManagementMouseClicked1(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStockManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnHRManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCusManagement))
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCusManagement)
                    .addComponent(btnStockManagement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHRManagement)
                    .addComponent(btnFinManagement))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStockManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockManagementMouseClicked
        StockManagementWindow.getInstance().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStockManagementMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnCusManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCusManagementMouseClicked
        new CustomerManagementWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCusManagementMouseClicked

    private void btnHRManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHRManagementMouseClicked
        new HRManagementWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHRManagementMouseClicked

    private void btnFinManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinManagementMouseClicked
        new FinanceManagementWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFinManagementMouseClicked

    private void btnStockManagementMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockManagementMouseClicked1
        StockManagementWindow.getInstance().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStockManagementMouseClicked1

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCusManagement;
    private javax.swing.JButton btnFinManagement;
    private javax.swing.JButton btnHRManagement;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnStockManagement;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
