/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer_intaface;

import HMS_Database.MyDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Prabas Gayadeeptha
 */
public class frmHall extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmHall
     */
    
         Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    static final String DB_URL = "jdbc:mysql://localhost/hms";

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "";
    
    public frmHall() {
        initComponents();
        
                jpanelHAdd.setVisible(false);
        jpanelHView.setVisible(true);
        jpanelHUpdate.setVisible(false);
        jpanelHDelete.setVisible(false);
        
          conn=MyDBConnection.Myconnect();
        
       
         
         update_table();
    }
    
    
    private void update_table(){
        
        try{
            String sql = "SELECT Booking_ID,Customer_ID,Reserve_date, Hall_no from hall ";
            //String sql = "SELECT id,f_name,l_name,category from trainers ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            htable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null,e);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMenu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jpanelHView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        htable = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        emp_background = new javax.swing.JLabel();
        jpanelHAdd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hall = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Reserve_date = new com.toedter.calendar.JDateChooser();
        pearl = new javax.swing.JRadioButton();
        ruby = new javax.swing.JRadioButton();
        emp_background1 = new javax.swing.JLabel();
        jpanelHUpdate = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        c_name = new javax.swing.JTextField();
        nic_no = new javax.swing.JTextField();
        contact_no = new javax.swing.JTextField();
        e_mail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        b_id = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        res_date = new com.toedter.calendar.JDateChooser();
        hpearl = new javax.swing.JRadioButton();
        hruby = new javax.swing.JRadioButton();
        emp_background2 = new javax.swing.JLabel();
        jpanelHDelete = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        booking = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btndelsearch = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        custname = new javax.swing.JTextField();
        emp_background3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer_Images/MenuBar_Back_Main_Customer.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel7.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel7.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelHView.setMinimumSize(new java.awt.Dimension(1190, 500));
        jpanelHView.setPreferredSize(new java.awt.Dimension(1190, 500));
        jpanelHView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        htable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Reserving Date", "Hall"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(htable);

        jpanelHView.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 849, 280));

        jButton14.setText("Refresh");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jpanelHView.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 309, -1, 39));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jpanelHView.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 500));

        jLayeredPane1.add(jpanelHView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 500));

        jpanelHAdd.setMinimumSize(new java.awt.Dimension(1190, 500));
        jpanelHAdd.setPreferredSize(new java.awt.Dimension(1190, 500));
        jpanelHAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Booking ID :");
        jpanelHAdd.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        jLabel2.setText("Customer ID :");
        jpanelHAdd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        jLabel3.setText("Customer Name :");
        jpanelHAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        jLabel4.setText("NIC Number :");
        jpanelHAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, -1, -1));

        jLabel5.setText("Contact Number");
        jpanelHAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));

        jLabel6.setText("E-mail :");
        jpanelHAdd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setText("Reserving Date :");
        jpanelHAdd.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 24, -1, -1));

        hall.setText("Hall :");
        jpanelHAdd.add(hall, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 101, -1, -1));
        jpanelHAdd.add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 21, 80, -1));
        jpanelHAdd.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 59, 80, -1));
        jpanelHAdd.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 98, 80, -1));
        jpanelHAdd.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 139, 80, -1));
        jpanelHAdd.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 179, 80, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jpanelHAdd.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 217, 80, -1));

        jLabel9.setText("(Max 150)");
        jpanelHAdd.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 101, -1, -1));

        jLabel10.setText("(Max 600)");
        jpanelHAdd.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 142, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Reservation-50.png"))); // NOI18N
        jButton8.setText("Reserve");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jpanelHAdd.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 275, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancel-50.png"))); // NOI18N
        jButton9.setText("Cancel");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jpanelHAdd.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 275, -1, -1));

        jLabel11.setText("Total :");
        jpanelHAdd.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 243, -1, -1));

        Reserve_date.setDateFormatString("yyyy-MM-dd");
        jpanelHAdd.add(Reserve_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 21, 120, -1));

        pearl.setText("Hall Pearl");
        pearl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pearlMouseClicked(evt);
            }
        });
        pearl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pearlActionPerformed(evt);
            }
        });
        jpanelHAdd.add(pearl, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 97, -1, -1));

        ruby.setText("Hall Ruby");
        ruby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rubyActionPerformed(evt);
            }
        });
        jpanelHAdd.add(ruby, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 138, -1, -1));

        emp_background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background1.setPreferredSize(new java.awt.Dimension(1190, 570));
        jpanelHAdd.add(emp_background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        jLayeredPane1.add(jpanelHAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpanelHUpdate.setMinimumSize(new java.awt.Dimension(1190, 500));
        jpanelHUpdate.setPreferredSize(new java.awt.Dimension(1190, 500));
        jpanelHUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Customer ID :");
        jpanelHUpdate.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));

        jLabel13.setText("Customer Name :");
        jpanelHUpdate.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jLabel14.setText("NIC Number :");
        jpanelHUpdate.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, -1, -1));

        jLabel15.setText("Contact Number");
        jpanelHUpdate.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, -1, -1));

        jLabel16.setText("E-mail :");
        jpanelHUpdate.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 228, -1, -1));

        jLabel17.setText("Reserving Date :");
        jpanelHUpdate.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 31, -1, -1));

        jLabel18.setText("Hall :");
        jpanelHUpdate.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 77, -1, -1));
        jpanelHUpdate.add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 74, 80, -1));

        c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameActionPerformed(evt);
            }
        });
        jpanelHUpdate.add(c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 114, 80, -1));
        jpanelHUpdate.add(nic_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 152, 80, -1));
        jpanelHUpdate.add(contact_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 190, 80, -1));
        jpanelHUpdate.add(e_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 228, 80, -1));

        jLabel19.setText("(Max 150)");
        jpanelHUpdate.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 77, -1, -1));

        jLabel20.setText("(Max 600)");
        jpanelHUpdate.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 106, -1, -1));

        jLabel22.setText("Total :");
        jpanelHUpdate.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 189, -1, -1));

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_search_172546.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jpanelHUpdate.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 22, -1, -1));

        jLabel23.setText("Booking ID :");
        jpanelHUpdate.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));
        jpanelHUpdate.add(b_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 28, 80, -1));

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Restart-50.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jpanelHUpdate.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 239, -1, -1));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancel-50.png"))); // NOI18N
        jButton13.setText("Cancel");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jpanelHUpdate.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 239, -1, -1));

        res_date.setDateFormatString("yyyy-MM-dd");
        jpanelHUpdate.add(res_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 22, 142, -1));

        hpearl.setText("Hall Pearl");
        hpearl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpearlActionPerformed(evt);
            }
        });
        jpanelHUpdate.add(hpearl, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 73, -1, -1));

        hruby.setText("Hall Ruby");
        hruby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrubyActionPerformed(evt);
            }
        });
        jpanelHUpdate.add(hruby, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 102, -1, -1));

        emp_background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background2.setPreferredSize(new java.awt.Dimension(1190, 570));
        jpanelHUpdate.add(emp_background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        jLayeredPane1.add(jpanelHUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpanelHDelete.setMinimumSize(new java.awt.Dimension(1190, 500));
        jpanelHDelete.setPreferredSize(new java.awt.Dimension(1190, 500));
        jpanelHDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Booking ID :");
        jpanelHDelete.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 83, -1));
        jpanelHDelete.add(booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 46, 110, -1));

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Delete-50.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jpanelHDelete.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 256, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancel-50.png"))); // NOI18N
        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jpanelHDelete.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 256, -1, -1));

        btndelsearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btndelsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_search_172546.png"))); // NOI18N
        btndelsearch.setText("Search");
        btndelsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelsearchActionPerformed(evt);
            }
        });
        jpanelHDelete.add(btndelsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 40, -1, -1));

        jLabel24.setText("Customer Name :");
        jpanelHDelete.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));
        jpanelHDelete.add(custname, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 79, 110, -1));

        emp_background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background3.setPreferredSize(new java.awt.Dimension(1190, 570));
        jpanelHDelete.add(emp_background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        jLayeredPane1.add(jpanelHDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1190, 500));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Back-50.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Add-50.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Restart-50.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Delete-50.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-View Details-50.png"))); // NOI18N
        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        update_table();

    }//GEN-LAST:event_jButton14ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {

            if(cid.getText().isEmpty()||cname.getText().isEmpty()||nic.getText().isEmpty()||
                contact.getText().isEmpty()||email.getText().isEmpty()||((JTextField)Reserve_date.getDateEditor().getUiComponent()).getText().isEmpty()||
                hallres.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Enter Valid Inputs");}

            else{
                String sql = "Insert into customer (Customer_ID,Booking_ID,Customer_name,NIC,Contact_no,email) values (?,?,?,?,?,?)";

                pst=conn.prepareStatement(sql);

                //pst.setString(1, jTextField1.getText());
                pst.setString(1, cid.getText());
                pst.setString(2, bid.getText());
                pst.setString(3, cname.getText());

                boolean status = ValidationO.nicValidation(nic.getText());
                if(status){

                    pst.setString(4, nic.getText());
                } else {

                    JOptionPane.showMessageDialog(null,"Enter Valid NIC");
                }

                pst.setString(5, contact.getText());

                boolean status1 = ValidationO.validateEmail(email.getText());
                if(status1){

                    pst.setString(6, email.getText());
                } else {

                    JOptionPane.showMessageDialog(null,"Enter Valid Email");
                }

                pst.execute();

                String sql1 = "Insert into hall (Booking_ID,Customer_ID,Reserve_date,Hall_no) values (?,?,?,?)" ;

                pst=conn.prepareStatement(sql1);

                pst.setString(1, bid.getText());
                pst.setString(2, cid.getText());
                pst.setString(3, ((JTextField)Reserve_date.getDateEditor().getUiComponent()).getText());
                pst.setString(4,hallres);

                pst.execute();

                JOptionPane.showMessageDialog(null, "Record Saved");
            }
        }
        catch(Exception e){

            //JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        bid.setText(null);
        cid.setText(null);
        cname.setText(null);
        nic.setText(null);
        contact.setText(null);
        email.setText(null);
        Reserve_date.setDate(null);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void pearlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pearlMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_pearlMouseClicked

    private void pearlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pearlActionPerformed
        // TODO add your handling code here:
        hallres = "Pearl";

        if(pearl.isSelected())
        ruby.setSelected(false);
    }//GEN-LAST:event_pearlActionPerformed

    private void rubyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rubyActionPerformed
        // TODO add your handling code here:
        hallres="Ruby";

        if(ruby.isSelected())
        pearl.setSelected(false);
    }//GEN-LAST:event_rubyActionPerformed

    private void c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nameActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String Search = b_id.getText();

        try{
            //String opt = txt_eid.getText();

            String sql = "SELECT Customer_ID,Customer_name,NIC,Contact_no,email from customer where Booking_ID LIKE '"+Search+"%'";
            pst =conn.prepareStatement(sql);
            rs= (ResultSet) pst.executeQuery(sql);

            if (rs.next()){

                String add1=rs.getString("Customer_ID");
                c_id.setText(add1);

                String add2=rs.getString("Customer_name");
                c_name.setText(add2);

                String add3=rs.getString("NIC");
                nic_no.setText(add3);

                String add4=rs.getString("Contact_no");
                contact_no.setText(add4);

                String add5=rs.getString("email");
                e_mail.setText(add5);

                String Search1 = b_id.getText();

            }
        }catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

        try{
            //String opt = txt_eid.getText();
            {

                String sql1 = "SELECT Reserve_date,Hall_no from hall where Booking_ID LIKE '"+Search+"%'";
                pst =conn.prepareStatement(sql1);
                rs=  (ResultSet)pst.executeQuery(sql1);

                if (rs.next()){

                    String add6=rs.getString("Reserve_date");
                    java.util.Date date;
                    try{
                        date = new SimpleDateFormat("yyyy-MM-dd").parse(add6);
                        res_date.setDate(date);

                    } catch (ParseException e) {

                    }

                    String add7=rs.getString("Hall_no");
                    if(add7.equals("Pearl")) {
                        hpearl.setSelected(true);
                        hruby.setSelected(false);
                    }
                    else {
                        hruby.setSelected(true);
                        hpearl.setSelected(false);

                    }

                }

                else{
                    JOptionPane.showMessageDialog(null, "'"+Search+"' Is not a Registered Member");
                }
            }
        }catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

    }//GEN-LAST:event_btnsearchActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:

        try{

            String value1= b_id.getText();
            String value2= c_name.getText();
            String value3= nic_no.getText();
            String value4= contact_no.getText();
            String value5= email.getText();

            String sql= "update customer set Customer_name='"+value2+"',NIC='"+value3+"',Contact_no='"+value4+"',email='"+value5+"' where Booking_ID = '"+value1+"'";
            pst= conn.prepareStatement(sql);
            pst.execute();

            String value6= b_id.getText();
            String value7= c_name.getText();
            String value8= ((JTextField)res_date.getDateEditor().getUiComponent()).getText();
            String value9=hallres1;

            String sql1= "update hall set Reserve_date='"+value8+"',Hall_no='"+value9+"' where Booking_ID = '"+value1+"'";
            pst= conn.prepareStatement(sql1);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Record Updated");
        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        //update_table();
        //clear_table();

    }//GEN-LAST:event_btn_updateActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        b_id.setText(null);
        c_id.setText(null);
        c_name.setText(null);
        nic_no.setText(null);
        contact_no.setText(null);
        e_mail.setText(null);
        res_date.setDate(null);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void hpearlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpearlActionPerformed

        hallres1 = "Pearl";

        if(hpearl.isSelected())
        hruby.setSelected(false);
    }//GEN-LAST:event_hpearlActionPerformed

    private void hrubyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrubyActionPerformed
        hallres1 = "Ruby";

        if(hruby.isSelected())
        hpearl.setSelected(false);
    }//GEN-LAST:event_hrubyActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String sql = "delete from customer  where Booking_ID = ?";
        try{

            pst = conn.prepareStatement(sql);

            pst.setString(1,booking.getText() );

            pst.execute ();
            //JOptionPane.showMessageDialog(null,"Record Deleted");

        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }

        String sql1 = "delete from hall where Booking_ID = ?";
        try{

            pst = conn.prepareStatement(sql1);

            pst.setString(1,booking.getText() );

            pst.execute ();
            JOptionPane.showMessageDialog(null,"Record Deleted");

        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        booking.setText(null);
        custname.setText(null);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void btndelsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelsearchActionPerformed
        // TODO add your handling code here:
        String Search = booking.getText();

        try{
            //String opt = txt_eid.getText();
            {

                String sql = "SELECT Customer_name from customer where Booking_ID LIKE '"+Search+"%'";
                pst =conn.prepareStatement(sql);
                rs= (ResultSet) pst.executeQuery(sql);

                if (rs.next()){

                    String add1=rs.getString("Customer_name");
                    custname.setText(add1);

                }

                else{
                    JOptionPane.showMessageDialog(null, "'"+Search+"' Is not a Registered Member");
                }
            }
        }catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        //clear_table();
    }//GEN-LAST:event_btndelsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmReservations fr = new frmReservations();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(fr).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jpanelHAdd.setVisible(true);
        jpanelHView.setVisible(false);
        jpanelHUpdate.setVisible(false);
        jpanelHDelete.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jpanelHAdd.setVisible(false);
        jpanelHView.setVisible(false);
        jpanelHUpdate.setVisible(true);
        jpanelHDelete.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jpanelHAdd.setVisible(false);
        jpanelHView.setVisible(false);
        jpanelHUpdate.setVisible(false);
        jpanelHDelete.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jpanelHAdd.setVisible(false);
        jpanelHView.setVisible(true);
        jpanelHUpdate.setVisible(false);
        jpanelHDelete.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    private com.toedter.calendar.JDateChooser Reserve_date;
    private javax.swing.JTextField b_id;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField booking;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelsearch;
    private javax.swing.JButton btnsearch;
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField c_name;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField contact_no;
    private javax.swing.JTextField custname;
    private javax.swing.JTextField e_mail;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emp_background;
    private javax.swing.JLabel emp_background1;
    private javax.swing.JLabel emp_background2;
    private javax.swing.JLabel emp_background3;
    private javax.swing.JLabel hall;
    private javax.swing.JRadioButton hpearl;
    private javax.swing.JRadioButton hruby;
    private javax.swing.JTable htable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelHAdd;
    private javax.swing.JPanel jpanelHDelete;
    private javax.swing.JPanel jpanelHUpdate;
    private javax.swing.JPanel jpanelHView;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField nic_no;
    private javax.swing.JRadioButton pearl;
    private com.toedter.calendar.JDateChooser res_date;
    private javax.swing.JRadioButton ruby;
    // End of variables declaration//GEN-END:variables
private String hallres;
private String hallres1;

}
