/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event_Interface;

import HMS_Database.MyDBConnection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class Bill extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        con = MyDBConnection.Myconnect();

        update_table();
    }

    private void update_table() {

        try {
            String sql = "SELECT Billno,eventId,date,extracharge,hotelcharge,service_charge,total from event_bill";

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            tbbill.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }
        public void tableload1()
        {
            try{
                String sql4="SELECT * from event_bill";
                pst=con.prepareStatement(sql4);
                rs=pst.executeQuery();
                
                tbbill.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                
                System.out.println(e);
            }
    
        }
    

private void clear_table() {

        billbox.setText(null);
        eventIdbox1.setText(null);
        datebox1.setDate(null);
        extrachargebox.setText(null);
        hotelchargebox.setText(null);
        servicechargebox.setText(null);
        totalbox.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        billbox = new javax.swing.JTextField();
        eventIdbox1 = new javax.swing.JTextField();
        datebox1 = new com.toedter.calendar.JDateChooser();
        extrachargebox = new javax.swing.JTextField();
        totalbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbill = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        hotelchargebox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        servicechargebox = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        emp_background = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        PnlMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Bill");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 11, 140, -1));

        jLabel2.setText("Bill No");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 108, -1, -1));

        jLabel3.setText("EventId");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 170, -1, -1));

        jLabel4.setText("Date");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 225, -1, -1));

        jLabel5.setText("Extra Charge");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 290, -1, -1));

        jLabel6.setText("Total");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 476, 38, -1));
        jPanel2.add(billbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 105, 136, -1));
        jPanel2.add(eventIdbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 167, 136, -1));

        datebox1.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(datebox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 219, 136, -1));
        jPanel2.add(extrachargebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 287, 136, -1));

        totalbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalboxActionPerformed(evt);
            }
        });
        jPanel2.add(totalbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 470, 143, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\file-submit.png")); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 508, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\update.png")); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 508, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\delete.png")); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\reply-all-button.png")); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 511, 100, 30));

        tbbill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbbill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill No", "EventId", "Date", "Extra Charge", "Hotel Charge", "Service Charges", "Total"
            }
        ));
        tbbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbbill);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 66, 535, -1));

        jLabel7.setText("Hotel Charge");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 352, -1, -1));
        jPanel2.add(hotelchargebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 349, 143, -1));

        jLabel8.setText("Service Charges");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 397, -1, -1));
        jPanel2.add(servicechargebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 394, 143, -1));

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 90, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Cal Total");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Cal Discount");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        emp_background.setBackground(new java.awt.Color(0, 0, 0));
        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel2.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1250, 640));

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1190, 580));

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event_Images/MenuBar_Back_Main_Event.jpg"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel10.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel10.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            if (billbox.getText().isEmpty() || eventIdbox1.getText().isEmpty()
                    || ((JTextField) datebox1.getDateEditor().getUiComponent()).getText().isEmpty()
                    || extrachargebox.getText().isEmpty() || hotelchargebox.getText().isEmpty() || servicechargebox.getText().isEmpty() || totalbox.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Enter Valid Inputs");

            }

            String sql = "Insert into event_bill (Billno,eventId,date,extracharge,hotelcharge,service_charge,total) values(?,?,?,?,?,?,?)";
            pst = con.prepareStatement(sql);

            pst.setString(1, billbox.getText());
            pst.setString(2, eventIdbox1.getText());

            pst.setString(3, ((JTextField) datebox1.getDateEditor().getUiComponent()).getText());
            pst.setString(4, extrachargebox.getText());
            pst.setString(5, hotelchargebox.getText());
            pst.setString(6, servicechargebox.getText());
            pst.setString(7, totalbox.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Record Saved");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

        update_table();
        clear_table();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            String value1 = billbox.getText();
            String value2 = eventIdbox1.getText();
            String value3 = ((JTextField) datebox1.getDateEditor().getUiComponent()).getText();
            String value4 = extrachargebox.getText();
            String value5 = hotelchargebox.getText();
            String value6 = servicechargebox.getText();
            String value7 = totalbox.getText();

            String sql = "update event_bill set Billno='" + value1 + "',EventId='" + value2 + "',date='" + value3 + "',extracharge='" + value4 + "',hotelcharge='" + value5 + "',service_charge='" + value6 + "',total='" + value7 + "' where Billno = '" + value1 + "'";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Updated");
        } catch (HeadlessException | SQLException e) {

            JOptionPane.showMessageDialog(null, e);

        }
        tableload1();
        update_table();
        clear_table();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String sql = "delete from event_bill where Billno = ?";
        try {

            pst = con.prepareStatement(sql);

            pst.setString(1, billbox.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Deleted");

        } catch (HeadlessException | SQLException e) {

            JOptionPane.showMessageDialog(null, e);

        }
        update_table();
        clear_table();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EventManagement em = new EventManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(em).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbillMouseClicked

        try {
            int row = tbbill.getSelectedRow();
            String Table_click = (tbbill.getModel().getValueAt(row, 0).toString());
            String sql = "select * from event_bill where Billno='" + Table_click + "'";
            pst = con.prepareStatement(sql);
            rs = (ResultSet) pst.executeQuery(sql);
            if (rs.next()) {

                String add1 = rs.getString("Billno");
                billbox.setText(add1);

                String add2 = rs.getString("eventId");
                eventIdbox1.setText(add2);

                String add3 = rs.getString("Date");
                java.util.Date date;
                try {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(add3);

                    datebox1.setDate(date);
                } catch (ParseException ex) {

                }

                String add4 = rs.getString("extracharge");
                extrachargebox.setText(add4);

                String add5 = rs.getString("hotelcharge");
                hotelchargebox.setText(add5);

                String add6 = rs.getString("service_charge");
                servicechargebox.setText(add6);

                String add7 = rs.getString("total");
                totalbox.setText(add7);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbbillMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            JasperDesign jd = JRXmlLoader.load("D:\\SLIIT\\2nd Year\\2nd Semester\\ITP - Information Technology Project\\Project\\Hotel_Management_System(Selsan)\\Bill.jrxml");// Path for the Report 
            String sql = "SELECT * FROM `event_bill` ";// USer input of SQL
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(jp);
            
            } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //cal tot
        int one=Integer.parseInt(hotelchargebox.getText());
        int two=Integer.parseInt(servicechargebox.getText());
        int three=Integer.parseInt(extrachargebox.getText());
        
        String answer=String.valueOf(one+two+three);
        totalbox.setText(answer);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //cal dis
        int one=Integer.parseInt(hotelchargebox.getText());
        String answer=String.valueOf(one*10/100);
        servicechargebox.setText(answer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JTextField billbox;
    private com.toedter.calendar.JDateChooser datebox1;
    private javax.swing.JLabel emp_background;
    private javax.swing.JTextField eventIdbox1;
    private javax.swing.JTextField extrachargebox;
    private javax.swing.JTextField hotelchargebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField servicechargebox;
    private javax.swing.JTable tbbill;
    private javax.swing.JTextField totalbox;
    // End of variables declaration//GEN-END:variables
}
