/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event_Interface;

import java.sql.PreparedStatement;
import HMS_Database.MyDBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class Client extends javax.swing.JInternalFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        con = MyDBConnection.connectDB();
       
        update_table();
    }
    
     private void update_table(){
        
        try{
            String sql = "SELECT ClientID,ClientName,ClientNIC,Email,Phonenumber,Date from event_client ";
            //String sql = "SELECT id,f_name,l_name,category from trainers ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            tblClient.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    private void clear_table(){
    
                  namebox.setText(null);
                  nicbox.setText(null);
                 emailbox.setText(null);
                  numberbox.setText(null);
                  datebox.setDate(null);
                  
                  
                  
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        namebox = new javax.swing.JTextField();
        nicbox = new javax.swing.JTextField();
        numberbox = new javax.swing.JTextField();
        datebox = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        emailbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        searchbox1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emp_background = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event_Images/MenuBar_Back_Main_Event.jpg"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel10.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel10.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Client");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 11, 143, 50));

        jLabel3.setText("Client Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 147, 70, -1));

        jLabel4.setText("Client NIC");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 194, 70, -1));

        jLabel5.setText("Phone Number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 277, -1, -1));

        jLabel6.setText("Date");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 321, 70, -1));

        jLabel8.setText("Email");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 239, 70, 20));

        btnAdd.setBackground(new java.awt.Color(153, 0, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event_Interface/file-submit.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 520, 130, 40));

        btnUpdate.setBackground(new java.awt.Color(153, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\Image\\update.png")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 521, -1, 40));

        btnDelete.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\Image\\delete.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 100, 40));

        btnBack.setBackground(new java.awt.Color(153, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\Image\\reply-all-button.png")); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));
        jPanel2.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 144, 148, -1));

        nicbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicboxActionPerformed(evt);
            }
        });
        jPanel2.add(nicbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 191, 148, -1));
        jPanel2.add(numberbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 275, 148, -1));

        datebox.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 321, 148, -1));

        tblClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ClientId", "Client Name", "Client NIC", "Email", "Phone Number", "Date"
            }
        ));
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClient);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 67, 793, 308));
        jPanel2.add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 237, 148, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 520, 90, 40));

        searchbox1.setBackground(new java.awt.Color(153, 0, 0));
        searchbox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbox1.setForeground(new java.awt.Color(255, 255, 255));
        searchbox1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\Image\\file.png")); // NOI18N
        searchbox1.setText("Search");
        searchbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbox1ActionPerformed(evt);
            }
        });
        jPanel2.add(searchbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, 120, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 100, 30));

        jLabel7.setText("Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 80, 20));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel2.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1200, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        try{

            if(namebox.getText().isEmpty()||nicbox.getText().isEmpty()||emailbox.getText().isEmpty()||
                numberbox.getText().isEmpty()||((JTextField)datebox.getDateEditor().getUiComponent()).getText().isEmpty())

            {

                JOptionPane.showMessageDialog(null,"Enter Valid Inputs");

            }

            String sql ="Insert into event_client(ClientName,ClientNIC,Email,Phonenumber,Date) values(?,?,?,?,?)";
            pst= con.prepareStatement(sql);

            pst.setString(1,namebox.getText());
            boolean status2= Validation.nicValidation(nicbox.getText());
            if (status2){
                pst.setString(2,nicbox.getText());
            }else{
                JOptionPane.showMessageDialog(null, "Enter Valid nic");
            }
            boolean statusl = Validation.emailValidate(emailbox.getText());
            if (statusl){
                pst.setString(3,emailbox.getText());
            }else{
                JOptionPane.showMessageDialog(null, "Enter Valid Email");
            }

            pst.setString(4,numberbox.getText());
            pst.setString(5,((JTextField)datebox.getDateEditor().getUiComponent()).getText());

            pst.execute();

            JOptionPane.showMessageDialog(null,"Record Saved");

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);

        }

        update_table();
        clear_table();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        try{

            String value1= namebox.getText();
            String value2= nicbox.getText();
            String value3= emailbox.getText();
            String value4= numberbox.getText();
            String value5= ((JTextField)datebox.getDateEditor().getUiComponent()).getText();

            String sql= "update event_client set ClientName='"+value1+"',Email='"+value3+"',Phonenumber='"+value4+"',Date='"+value5+"' where ClientNIC = '"+value2+"'";
            pst= con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Record Updated");
        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        update_table();
        clear_table();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        String sql = "delete from event_client where ClientNIC = ?";
        try{

            pst = con.prepareStatement(sql);

            pst.setString(1,nicbox.getText() );

            pst.execute ();
            JOptionPane.showMessageDialog(null,"Record Deleted");

        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        update_table();
        clear_table();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        EventManagement em = new EventManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(em).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void nicboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicboxActionPerformed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked

        try{
            int row=tblClient.getSelectedRow();
            String Table_click=(tblClient.getModel().getValueAt(row, 0).toString());
            String sql="select * from event_client where ClientID='"+Table_click+"'";
            pst=con.prepareStatement(sql);
            rs= (ResultSet) pst.executeQuery(sql);
            if (rs.next()){

                String add1=rs.getString("ClientName");
                namebox.setText(add1);

                String add2=rs.getString("ClientNIC");
                nicbox.setText(add2);

                String add3=rs.getString("Email");
                emailbox.setText(add3);

                String add4=rs.getString("Phonenumber");
                numberbox.setText(add4);

                String add5=rs.getString("Date");
                java.util.Date date;
                try {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(add5);

                    datebox.setDate(date);
                }
                catch (ParseException ex) {

                }

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_tblClientMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            JasperDesign jd = JRXmlLoader.load("D:\\SLIIT\\2nd Year\\2nd Semester\\ITP - Information Technology Project\\Project\\Hotel_Management_System(Selsan)\\Client.jrxml");// Path for the Report 
            String sql = "SELECT * FROM event_client";// USer input of SQL
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(jp);
            
            } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbox1ActionPerformed
        // search
        
        String name = jTextField1.getText();

        String sql = "SELECT ClientID,ClientName,ClientNIC,Email,Phonenumber,Date from event_client where ClientName LIKE '%" + name + "%'";

        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            tblClient.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_searchbox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JDateChooser datebox;
    private javax.swing.JTextField emailbox;
    private javax.swing.JLabel emp_background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField nicbox;
    private javax.swing.JTextField numberbox;
    private javax.swing.JButton searchbox1;
    private javax.swing.JTable tblClient;
    // End of variables declaration//GEN-END:variables
}
