/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event_Interface;

import HMS_Database.MyDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class Event extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Event
     */
    public Event() {
        initComponents();
        con = MyDBConnection.Myconnect();
        update_table();
      //  tableLoad();
       // update_table();
    }

    private void update_table() {

        try {
            String sql = "SELECT event_Id,event_type,date,pax,cost from event_event ";
            //String sql = "SELECT id,f_name,l_name,category from trainers ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            //tab1.Service.setModel(DbUtils.resultSetToTableModel(rs));
            et3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void clear_table() {

        eventIdbox3.setText(null);
        typebox3.setSelectedItem("Type");
        datebox4.setDate(null);

        paxbox3.setText(null);
        Costbox3.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eventIdbox3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        typebox3 = new javax.swing.JComboBox<>();
        paxbox3 = new javax.swing.JTextField();
        Costbox3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        et3 = new javax.swing.JTable();
        datebox4 = new com.toedter.calendar.JDateChooser();
        btn_report = new javax.swing.JButton();
        emp_background = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        eventIdbox4 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event_Images/MenuBar_Back_Main_Event.jpg"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel10.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel10.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 680));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\file-submit.png")); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 90, 40));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\update.png")); // NOI18N
        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, 40));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\delete.png")); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 100, 40));

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\reply-all-button.png")); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Event");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 196, 56));

        jLabel2.setText("EventId");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 124, -1, -1));
        jPanel2.add(eventIdbox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 148, -1));

        jLabel3.setText("Event Type");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 178, -1, -1));

        jLabel4.setText("Date");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 222, -1, -1));

        jLabel5.setText("Pax");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 269, -1, -1));

        jLabel6.setText("Cost");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 321, -1, -1));

        typebox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Indoor", "Outdoor", "Catering" }));
        jPanel2.add(typebox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 175, 148, -1));
        jPanel2.add(paxbox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 268, 148, -1));

        Costbox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Costbox3ActionPerformed(evt);
            }
        });
        jPanel2.add(Costbox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 318, 148, -1));

        et3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EventId", "Event type", "Date", "Pax", "Cost"
            }
        ));
        et3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                et3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(et3);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 94, -1, 297));

        datebox4.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(datebox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 222, 148, 28));

        btn_report.setBackground(new java.awt.Color(0, 102, 0));
        btn_report.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_report.setForeground(new java.awt.Color(255, 255, 255));
        btn_report.setText("Report");
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        jPanel2.add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 90, 40));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel2.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, -1));

        jTextField2.setText("jTextField2");
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, -1, -1));

        jTextField3.setText("jTextField3");
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));
        jPanel2.add(eventIdbox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 121, 148, -1));

        jTextField4.setText("jTextField4");
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1190, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            if (eventIdbox3.getText().isEmpty() || typebox3.getSelectedItem().equals("type") || ((JTextField) datebox4.getDateEditor().getUiComponent()).getText().isEmpty()
                    || paxbox3.getText().isEmpty() || Costbox3.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Enter Valid Inputs");

            }

            String sql = "Insert into event_event(event_Id,event_type,date,pax,cost) values(?,?,?,?,?)";
            pst = con.prepareStatement(sql);

            pst.setString(1, eventIdbox3.getText());
            String value = typebox3.getSelectedItem().toString();
            pst.setString(2, value);
            pst.setString(3, ((JTextField) datebox4.getDateEditor().getUiComponent()).getText());
            pst.setString(4, paxbox3.getText());
            pst.setString(5, Costbox3.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Record Saved");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

        update_table();
        clear_table();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            String value1 = eventIdbox3.getText();
            String value2 = typebox3.getSelectedItem().toString();
            String value3 = ((JTextField) datebox4.getDateEditor().getUiComponent()).getText();
            String value4 = paxbox3.getText();
            String value5 = Costbox3.getText();

            String sql = "update event_event set event_type='" + value2 + "',date='" + value3 + "',pax='" + value4 + "',cost='" + value5 + "' where event_Id = '" + value1 + "'";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Updated");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
        update_table();
        clear_table();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String sql = "delete from event_event where event_Id = ?";
        try {

            pst = con.prepareStatement(sql);

            pst.setString(1, eventIdbox3.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Deleted");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
        update_table();
        clear_table();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        EventManagement em = new EventManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(em).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Costbox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Costbox3ActionPerformed
        // TODO add your handling code  here:
    }//GEN-LAST:event_Costbox3ActionPerformed

    private void et3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_et3MouseClicked
        try {
            int row = et3.getSelectedRow();
            String Table_click = (et3.getModel().getValueAt(row, 0).toString());
            String sql = "select * from event_event where event_Id='" + Table_click + "'";
            pst = con.prepareStatement(sql);
            rs = (ResultSet) pst.executeQuery(sql);
            if (rs.next()) {

                String add1 = rs.getString("event_Id");
                eventIdbox3.setText(add1);

                String add2 = rs.getString("event_type");
                typebox3.setSelectedItem(add2);

                String add3 = rs.getString("date");
                java.util.Date date;
                try {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(add3);

                    datebox4.setDate(date);
                } catch (ParseException ex) {

                }
                String add4 = rs.getString("pax");
                paxbox3.setText(add4);
                String add5 = rs.getString("cost");
                Costbox3.setText(add5);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_et3MouseClicked

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
try {
            JasperDesign jd = JRXmlLoader.load("D:\\SLIIT\\2nd Year\\2nd Semester\\ITP - Information Technology Project\\Project\\Hotel_Management_System(Selsan)\\Event.jrxml");// Path for the Report 
            String sql = "SELECT * FROM `event_event` ";// USer input of SQL
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(jp);
            
            } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Costbox3;
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton btn_report;
    private com.toedter.calendar.JDateChooser datebox4;
    private javax.swing.JLabel emp_background;
    private javax.swing.JTable et3;
    private javax.swing.JTextField eventIdbox3;
    private javax.swing.JTextField eventIdbox4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField paxbox3;
    private javax.swing.JComboBox<String> typebox3;
    // End of variables declaration//GEN-END:variables

    private void tableLoad() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
