/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event_Interface;

import HMS_Database.MyDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class Service extends javax.swing.JInternalFrame {

    
     Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Service
     */
    public Service() {
        initComponents();
        con = MyDBConnection.Myconnect();
        update_table();
    }
    
    private void update_table(){
        
        try{
            String sql = "SELECT serviceid,eventId,tables,chairs,poruwa,music,cost_charg from event_service ";
            //String sql = "SELECT id,f_name,l_name,category from trainers ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            //tab1.Service.setModel(DbUtils.resultSetToTableModel(rs));
            tab1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
        private void clear_table(){
    
                  serviceidbox.setText(null);
                  eventidbox1.setText(null);
                  tablebox1.setText(null);
                  chairbox1.setText(null); 
                  poruwabox1.setSelectedItem("Type");
                 musicbox1.setSelectedItem("Type");
                  costchargebox.setText(null); 
                  
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        serviceidbox = new javax.swing.JTextField();
        eventidbox1 = new javax.swing.JTextField();
        tablebox1 = new javax.swing.JTextField();
        chairbox1 = new javax.swing.JTextField();
        poruwabox1 = new javax.swing.JComboBox<>();
        musicbox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        costchargebox = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        emp_background = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event_Images/MenuBar_Back_Main_Event.jpg"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel10.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel10.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Services");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabel2.setText("ServiceID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 89, -1, -1));

        jLabel3.setText("Event ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 133, -1, -1));

        jLabel4.setText("Tables");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 193, -1, -1));

        jLabel5.setText("Chairs");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 251, -1, -1));

        jLabel6.setText("Poruwa");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 314, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Music");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 368, 36, 23));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\file-submit.png")); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 90, 30));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\update.png")); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 110, 30));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\delete.png")); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 100, 30));

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tharaka\\Desktop\\reply-all-button.png")); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 110, 30));
        jPanel2.add(serviceidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 86, 116, -1));
        jPanel2.add(eventidbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 130, 116, -1));
        jPanel2.add(tablebox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 190, 116, -1));
        jPanel2.add(chairbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 248, 116, -1));

        poruwabox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "10 000", "15 000", "18 000", "20 000", " " }));
        jPanel2.add(poruwabox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 311, 116, -1));

        musicbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------", "2 Piece band", "3 Piece band", "Full Band", "DJ" }));
        jPanel2.add(musicbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 369, 116, -1));

        tab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ServiceID", "EventID", "Tables", "Chairs", "Poruwa", "Music", "cost charge"
            }
        ));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 741, 170));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cost charge");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 429, -1, -1));
        jPanel2.add(costchargebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 426, 116, -1));

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 80, 30));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel2.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1190, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{

            //  if(serviceidbox.getText().isEmpty()||eventidbox1.getText().isEmpty()||tablebox1.getText().isEmpty()||
                // chairbox1.getText().isEmpty()||poruwabox1.getSelectedItem().equals("type")||musicbox1.getSelectedItem().equals("type")||costchargebox.getText().isEmpty())

            {

                //JOptionPane.showMessageDialog(null,"Enter Valid Inputs");

            }

            String sql ="Insert into event_service(serviceid,eventId,tables,chairs,poruwa,music,cost_charg) values(?,?,?,?,?,?,?)";
            pst= con.prepareStatement(sql);

            pst.setString(1,serviceidbox.getText());
            pst.setString(2,eventidbox1.getText());
            pst.setString(3,tablebox1.getText());
            pst.setString(4,chairbox1.getText());
            String value = poruwabox1.getSelectedItem().toString();
            pst.setString (5,value);
            String value1 = musicbox1.getSelectedItem().toString();
            pst.setString (6,value1);
            pst.setString(7,costchargebox.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null,"Record Saved");

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);

        }

        update_table();
        clear_table();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//update
        try{

            String value1= serviceidbox.getText();
            String value2= eventidbox1.getText();
            String value3= tablebox1.getText();
            String value4= chairbox1.getText();
            String value5= poruwabox1.getSelectedItem().toString();
            String value6= musicbox1.getSelectedItem().toString();
            String value7= costchargebox.getText();

            String sql= "update event_service set tables='"+value3+"',chairs='"+value4+"',poruwa='"+value5+"',music='"+value6+"',cost_charg='"+value7+"'  where serviceId = '"+value1+"'";
            pst= con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Record Updated");
        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        update_table();
        clear_table();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String sql = "delete from event_service where serviceid = ?";
        try{

            pst = con.prepareStatement(sql);

            pst.setString(1,serviceidbox.getText() );

            pst.execute ();
            JOptionPane.showMessageDialog(null,"Record Deleted");

        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        update_table();
        clear_table();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EventManagement em = new EventManagement();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(em).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked

        try{
            int row=tab1.getSelectedRow();
            String Table_click=(tab1.getModel().getValueAt(row, 0).toString());
            String sql="select * from event_service where serviceId='"+Table_click+"'";
            pst=con.prepareStatement(sql);
            rs= (ResultSet) pst.executeQuery(sql);
            if (rs.next()){

                String add1=rs.getString("serviceId");
                serviceidbox.setText(add1);

                String add2=rs.getString("eventId");
                eventidbox1.setText(add2);

                String add3=rs.getString("tables");
                tablebox1.setText(add3);

                String add4=rs.getString("chairs");
                chairbox1.setText(add4);

                String add5=rs.getString("poruwa");
                poruwabox1.setSelectedItem(add5);

                String add6=rs.getString("music");
                musicbox1.setSelectedItem(add6);

                String add7=rs.getString("cost_charg");
                costchargebox.setText(add7);

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_tab1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            JasperDesign jd = JRXmlLoader.load("D:\\SLIIT\\2nd Year\\2nd Semester\\ITP - Information Technology Project\\Project\\Hotel_Management_System(Selsan)\\Service.jrxml");// Path for the Report 
            String sql = "SELECT * FROM event_service";// USer input of SQL
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(jp);
            
            } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JTextField chairbox1;
    private javax.swing.JTextField costchargebox;
    private javax.swing.JLabel emp_background;
    private javax.swing.JTextField eventidbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> musicbox1;
    private javax.swing.JComboBox<String> poruwabox1;
    private javax.swing.JTextField serviceidbox;
    private javax.swing.JTable tab1;
    private javax.swing.JTextField tablebox1;
    // End of variables declaration//GEN-END:variables
}
