/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer_Interface;

import HMS_Database.MyDBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Prabas Gayadeeptha
 */
public class frmRooms extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRooms
     */
         Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public frmRooms() {
        initComponents();
        jpanelRAdd.setVisible(false);
        jpanelRView.setVisible(true);
        jpanelRUpdate.setVisible(false);
        jpanelRDelete.setVisible(false);
        
        conn=MyDBConnection.connectDB();

        
        update_table();
    }
    
     private void update_table(){
        
        try{
            String sql = "SELECT Booking_ID,Customer_ID,Check_In_Date, Check_Out_Date,Room_type,no_of_rooms from room ";
            //String sql = "SELECT id,f_name,l_name,category from trainers ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            tbl_customer.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    private void clear_table() {
    
                  b_id.setText(null);
                  c_id.setText(null);
                  c_name.setText(null);
                  txtnic.setText(null);
                  txtcontact.setText(null);
                  txtemail.setText(null);
                  date1.setDate(null);
                  date2.setDate(null);
                  typetxt.setSelectedItem("-- Select Type--");
                  nrooms.setText(null);
                  
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jpanelRDelete = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        bookingtext = new javax.swing.JTextField();
        button_delete = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cusname = new javax.swing.JTextField();
        emp_background = new javax.swing.JLabel();
        jpanelRUpdate = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        b_id = new javax.swing.JTextField();
        c_id = new javax.swing.JTextField();
        c_name = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        typetxt = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        nrooms = new javax.swing.JTextField();
        emp_background1 = new javax.swing.JLabel();
        jpanelRView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_customer = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        emp_background2 = new javax.swing.JLabel();
        jpanelRAdd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        nic1 = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        indate = new com.toedter.calendar.JDateChooser();
        outdate = new com.toedter.calendar.JDateChooser();
        com_type = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        rooms = new javax.swing.JTextField();
        emp_background3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer_Images/MenuBar_Back_Main_Customer.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel7.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel7.setPreferredSize(new java.awt.Dimension(1190, 75));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Delete-50.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Restart-50.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Add-50.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-View Details-50.png"))); // NOI18N
        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Back-50.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1190, 500));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRDelete.setMinimumSize(new java.awt.Dimension(1190, 500));
        jpanelRDelete.setPreferredSize(new java.awt.Dimension(1190, 500));
        jpanelRDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Booking ID :");
        jpanelRDelete.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));
        jpanelRDelete.add(bookingtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 46, 110, -1));

        button_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Delete-50.png"))); // NOI18N
        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });
        jpanelRDelete.add(button_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 227, -1, -1));

        btcancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancel-50.png"))); // NOI18N
        btcancel.setText("Cancel");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });
        jpanelRDelete.add(btcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 227, -1, -1));

        search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_search_172546.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jpanelRDelete.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 40, -1, -1));

        jLabel15.setText("Customer Name :");
        jpanelRDelete.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));
        jpanelRDelete.add(cusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 84, 110, -1));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jpanelRDelete.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 500));

        jLayeredPane1.add(jpanelRDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpanelRUpdate.setMinimumSize(new java.awt.Dimension(1190, 500));
        jpanelRUpdate.setPreferredSize(new java.awt.Dimension(1190, 500));
        jpanelRUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setText("Booking ID :");
        jpanelRUpdate.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        jLabel65.setText("Customer ID :");
        jpanelRUpdate.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        jLabel66.setText("Customer Name :");
        jpanelRUpdate.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        jLabel67.setText("NIC Number :");
        jpanelRUpdate.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel68.setText("Contact Number");
        jpanelRUpdate.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, -1, -1));

        jLabel69.setText("E-mail :");
        jpanelRUpdate.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, -1, -1));

        jLabel70.setText("Check-In Date :");
        jpanelRUpdate.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 29, 82, -1));

        jLabel71.setText("Room Type :");
        jpanelRUpdate.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 112, 82, -1));
        jpanelRUpdate.add(b_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 26, 80, -1));
        jpanelRUpdate.add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 71, 80, -1));
        jpanelRUpdate.add(c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 109, 80, -1));
        jpanelRUpdate.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 147, 80, -1));
        jpanelRUpdate.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 185, 80, -1));
        jpanelRUpdate.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 223, 80, -1));

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Restart-50.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jpanelRUpdate.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 272, -1, -1));

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancel-50.png"))); // NOI18N
        btnclear.setText("Cancel");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jpanelRUpdate.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 272, -1, -1));

        jLabel72.setText("Check-out Date :");
        jpanelRUpdate.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 74, -1, -1));

        jLabel12.setText("Total :");
        jpanelRUpdate.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 317, -1, -1));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_search_172546.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jpanelRUpdate.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 20, -1, -1));

        date1.setDateFormatString("yyyy-MM-dd");
        jpanelRUpdate.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 20, 156, -1));

        date2.setDateFormatString("yyyy-MM-dd");
        jpanelRUpdate.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 71, 156, -1));

        typetxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Double Room", "Triple Room", "Family Room" }));
        jpanelRUpdate.add(typetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 110, 156, -1));

        jLabel14.setText("Number of Rooms :");
        jpanelRUpdate.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 150, -1, -1));
        jpanelRUpdate.add(nrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 148, 156, -1));

        emp_background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background1.setPreferredSize(new java.awt.Dimension(1190, 570));
        jpanelRUpdate.add(emp_background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 500));

        jLayeredPane1.add(jpanelRUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 500));

        jpanelRView.setMinimumSize(new java.awt.Dimension(1190, 500));
        jpanelRView.setPreferredSize(new java.awt.Dimension(1190, 500));
        jpanelRView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Check-in Date", "Check-out Date", "Room Type", "No of Rooms"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_customer);

        jpanelRView.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 889, 220));

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jpanelRView.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 305, -1, 55));

        emp_background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background2.setPreferredSize(new java.awt.Dimension(1190, 570));
        jpanelRView.add(emp_background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 500));

        jLayeredPane1.add(jpanelRView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jpanelRAdd.setMinimumSize(new java.awt.Dimension(1190, 500));
        jpanelRAdd.setPreferredSize(new java.awt.Dimension(1190, 500));
        jpanelRAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Booking ID :");
        jpanelRAdd.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        jLabel2.setText("Customer ID :");
        jpanelRAdd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        jLabel3.setText("Customer Name :");
        jpanelRAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("NIC Number :");
        jpanelRAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        jLabel5.setText("Contact Number");
        jpanelRAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));

        jLabel6.setText("E-mail :");
        jpanelRAdd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, -1));

        jLabel8.setText("Check-In Date :");
        jpanelRAdd.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 24, 82, -1));

        jLabel9.setText("Room Type :");
        jpanelRAdd.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 100, 82, -1));
        jpanelRAdd.add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 21, 80, -1));
        jpanelRAdd.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 59, 80, -1));

        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        jpanelRAdd.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 97, 80, -1));

        nic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nic1ActionPerformed(evt);
            }
        });
        jpanelRAdd.add(nic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 135, 80, -1));
        jpanelRAdd.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 173, 80, -1));
        jpanelRAdd.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 211, 80, -1));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Reservation-50.png"))); // NOI18N
        btn_save.setText("Reserve");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jpanelRAdd.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 324, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancel-50.png"))); // NOI18N
        jButton9.setText("Cancel");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jpanelRAdd.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 324, -1, -1));

        jLabel11.setText("Check-out Date :");
        jpanelRAdd.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 62, -1, -1));

        jLabel10.setText("Total :");
        jpanelRAdd.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 369, -1, -1));

        indate.setDateFormatString("yyyy-MM-dd");
        jpanelRAdd.add(indate, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 21, 140, -1));

        outdate.setDateFormatString("yyyy-MM-dd");
        jpanelRAdd.add(outdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 59, 140, -1));

        com_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " --Select Type--", "Double Room", "Triple Room", "Family Room" }));
        jpanelRAdd.add(com_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 97, 140, -1));

        jLabel13.setText("Number of Rooms :");
        jpanelRAdd.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 138, -1, -1));
        jpanelRAdd.add(rooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 135, 140, -1));

        emp_background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background3.setPreferredSize(new java.awt.Dimension(1190, 570));
        jpanelRAdd.add(emp_background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 500));

        jLayeredPane1.add(jpanelRAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -1, -1, -1));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1190, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jpanelRAdd.setVisible(false);
        jpanelRView.setVisible(false);
        jpanelRUpdate.setVisible(false);
        jpanelRDelete.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jpanelRAdd.setVisible(false);
        jpanelRView.setVisible(false);
        jpanelRUpdate.setVisible(true);
        jpanelRDelete.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jpanelRAdd.setVisible(true);
        jpanelRView.setVisible(false);
        jpanelRUpdate.setVisible(false);
        jpanelRDelete.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jpanelRAdd.setVisible(false);
        jpanelRView.setVisible(true);
        jpanelRUpdate.setVisible(false);
        jpanelRDelete.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmReservations fh = new frmReservations();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(fh).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        update_table();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void nic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nic1ActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        try {

            if(bid.getText().isEmpty()||cid.getText().isEmpty()||cname.getText().isEmpty()||nic1.getText().isEmpty()||
                contact.getText().isEmpty()||email1.getText().isEmpty()||((JTextField)indate.getDateEditor().getUiComponent()).getText().isEmpty()||
                ((JTextField)outdate.getDateEditor().getUiComponent()).getText().isEmpty()||com_type.getSelectedItem().equals(" --Select Type--"))
            {
                JOptionPane.showMessageDialog(null,"Enter Valid Inputs");}

            else{
                String sql = "Insert into customer (Customer_ID,Booking_ID,Customer_name,NIC,Contact_no,email) values (?,?,?,?,?,?)";

                pst=conn.prepareStatement(sql);

                //pst.setString(1, jTextField1.getText());
                pst.setString(1, cid.getText());
                pst.setString(2, bid.getText());
                pst.setString(3, cname.getText());

                boolean status = ValidationO.nicValidation(nic1.getText());
                if(status){

                    pst.setString(4, nic1.getText());
                } else {

                    JOptionPane.showMessageDialog(null,"Enter Valid NIC");
                }

                pst.setString(5, contact.getText());

                boolean status1 = ValidationO.validateEmail(email1.getText());
                if(status1){

                    pst.setString(6, email1.getText());
                } else {

                    JOptionPane.showMessageDialog(null,"Enter Valid Email");
                }

                pst.execute();

                String sql1 = "Insert into room (Booking_ID,Customer_ID,Check_In_Date,Check_Out_Date,Room_type,no_of_rooms) values (?,?,?,?,?,?)" ;

                pst=conn.prepareStatement(sql1);

                pst.setString(1, bid.getText());
                pst.setString(2, cid.getText());
                pst.setString(3, ((JTextField)indate.getDateEditor().getUiComponent()).getText());
                pst.setString(4, ((JTextField)outdate.getDateEditor().getUiComponent()).getText());
                String value = com_type.getSelectedItem().toString();//combo box
                pst.setString(5, value);
                pst.setString(6, rooms.getText());

                pst.execute();

                JOptionPane.showMessageDialog(null, "Record Saved");
            }
        }
        catch(Exception e){

            //JOptionPane.showMessageDialog(null, e);
        }

        //update_table();
        //clear_table();

        // TODO add your handling code here:
        //AddRoom();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        bid.setText("");
        cid.setText("");
        cname.setText("");
        nic1.setText("");
        contact.setText("");
        email1.setText("");
        indate.setDate(null);
        outdate.setDate(null);
        com_type.setSelectedItem("--Select Type--");
        rooms.setText(null);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        try{

            String value1= b_id.getText();
            String value2= c_name.getText();
            String value3= txtnic.getText();
            String value4= txtcontact.getText();
            String value5= txtemail.getText();

            String sql= "update customer set Customer_name='"+value2+"',NIC='"+value3+"',Contact_no='"+value4+"',email='"+value5+"' where Booking_ID = '"+value1+"'";
            pst= conn.prepareStatement(sql);
            pst.execute();

            String value6= b_id.getText();
            String value7= ((JTextField)date1.getDateEditor().getUiComponent()).getText();
            String value8= ((JTextField)date2.getDateEditor().getUiComponent()).getText();
            String value9= typetxt.getSelectedItem().toString();
            String value10= nrooms.getText();

            String sql1= "update room set Check_In_Date='"+value7+"',Check_Out_Date='"+value8+"',Room_type='"+value9+"',no_of_rooms='"+value10+"' where Booking_ID = '"+value1+"'";
            pst= conn.prepareStatement(sql1);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Record Updated");
        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        //update_table();
        clear_table();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed

        b_id.setText(null);
        c_id.setText(null);
        c_name.setText(null);
        txtnic.setText(null);
        txtcontact.setText(null);
        txtemail.setText(null);
        date1.setDate(null);
        date2.setDate(null);
        typetxt.setSelectedItem("-- Select Type--");
        nrooms.setText(null);
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String Search = b_id.getText();

        try{
            //String opt = txt_eid.getText();

            String sql = "SELECT Customer_ID,Customer_name,NIC,Contact_no,email from customer where Booking_ID LIKE '"+Search+"%'";
            pst =conn.prepareStatement(sql);
            rs= (ResultSet) pst.executeQuery(sql);

            if (rs.next()){

                String add1=rs.getString("Customer_ID");
                c_id.setText(add1);

                String add2=rs.getString("Customer_name");
                c_name.setText(add2);

                String add3=rs.getString("NIC");
                txtnic.setText(add3);

                String add4=rs.getString("Contact_no");
                txtcontact.setText(add4);

                String add5=rs.getString("email");
                txtemail.setText(add5);

                String Search1 = b_id.getText();

            }
        }catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

        try{
            //String opt = txt_eid.getText();
            {

                String sql1 = "SELECT Check_In_Date,Check_Out_Date,Room_type,no_of_rooms from room where Booking_ID LIKE '"+Search+"%'";
                pst =conn.prepareStatement(sql1);
                rs=  (ResultSet)pst.executeQuery(sql1);

                if (rs.next()){

                    String add6=rs.getString("Check_In_Date");
                    java.util.Date date;
                    try{
                        date = new SimpleDateFormat("yyyy-MM-dd").parse(add6);
                        date1.setDate(date);

                    } catch (ParseException e) {

                    }

                    String add7=rs.getString("Check_Out_Date");
                    //java.util.Date date;
                    try{
                        date = new SimpleDateFormat("yyyy-MM-dd").parse(add7);
                        date2.setDate(date);

                    } catch (ParseException e) {

                    }

                    String add8=rs.getString("Room_type");
                    typetxt.setSelectedItem(add8);

                    String add9=rs.getString("no_of_rooms");
                    nrooms.setText(add9);
                }

                else{
                    JOptionPane.showMessageDialog(null, "'"+Search+"' Is not a Registered Member");
                }
            }
        }catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

        // clear_table();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed

        String sql = "delete from customer  where Booking_ID = ?";
        try{

            pst = conn.prepareStatement(sql);

            pst.setString(1,bookingtext.getText() );

            pst.execute ();
            //JOptionPane.showMessageDialog(null,"Record Deleted");

        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }

        String sql1 = "delete from room where Booking_ID = ?";
        try{

            pst = conn.prepareStatement(sql1);

            pst.setString(1,bookingtext.getText() );

            pst.execute ();
            JOptionPane.showMessageDialog(null,"Record Deleted");

        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        //update_table();
        // clear_table();
    }//GEN-LAST:event_button_deleteActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed

        bookingtext.setText(null);
        cusname.setText(null);
    }//GEN-LAST:event_btcancelActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        String Search = bookingtext.getText();

        try{
            //String opt = txt_eid.getText();
            {

                String sql = "SELECT Customer_name from customer where Booking_ID LIKE '"+Search+"%'";
                pst =conn.prepareStatement(sql);
                rs= (ResultSet) pst.executeQuery(sql);

                if (rs.next()){

                    String add1=rs.getString("Customer_name");
                    cusname.setText(add1);

                }

                else{
                    JOptionPane.showMessageDialog(null, "'"+Search+"' Is not a Registered Member");
                }
            }
        }catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        clear_table();
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b_id;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bookingtext;
    private javax.swing.JButton btcancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton button_delete;
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField c_name;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JComboBox<String> com_type;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField cusname;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel emp_background;
    private javax.swing.JLabel emp_background1;
    private javax.swing.JLabel emp_background2;
    private javax.swing.JLabel emp_background3;
    private com.toedter.calendar.JDateChooser indate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelRAdd;
    private javax.swing.JPanel jpanelRDelete;
    private javax.swing.JPanel jpanelRUpdate;
    private javax.swing.JPanel jpanelRView;
    private javax.swing.JTextField nic1;
    private javax.swing.JTextField nrooms;
    private com.toedter.calendar.JDateChooser outdate;
    private javax.swing.JTextField rooms;
    private javax.swing.JButton search;
    private javax.swing.JTable tbl_customer;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnic;
    private javax.swing.JComboBox<String> typetxt;
    // End of variables declaration//GEN-END:variables
}
