/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRManagement;


import Main.Login;
import Main.MainWindow;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Irushi
 */
public class HRManagementWindow extends javax.swing.JFrame {
    private String curEID;
    private static HRManagementWindow instance;
    /**
     * Creates new form HRManagementWindow
     * @param eID
     */
    HRModel c = new HRModel();
    HRController hrm = new HRController();
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    java.util.Date date;
    String sql = "";


    
    public HRManagementWindow(String eID) {
        initComponents();
        curEID = eID;
        //jTabbedPane1.addTab("User", new User());
        this.setLocationRelativeTo(null);
        hrm.AutoGeneratePrimaryKey(lbl_eid, txt_empID, 'e', "employee", "Emp_ID");
        hrm.AutoGeneratePrimaryKey(lbl_iidVal, txt_interID, 'i', "interview_schedule", "interID");
        conn = (Connection) Main.MyDBConnection.Myconnect();
        HRController.loadTable(tbl_employee, "employee", "Emp_ID");
        HRController.loadTable(tbl_candidate, "candidate", "candidateID");
        HRController.loadTable(tbl_interview_schedule, "interview_schedule", "date");
        HRController.loadTable(tbl_attendance, "attendence", "attID");
        HRController.loadTable(tbl_job, "job", "jobid");
    }
    

        public void setEmployee() {
        c.setEmpID(txt_empID.getText());
        c.setFname(txt_fname.getText());
        c.setEmpgender(cmb_empgender.getSelectedItem().toString());
        c.setEmpnic(txt_nic.getText());
        c.setEmpdob(((JTextField) dc_startdate.getDateEditor().getUiComponent()).getText());
        c.setEmpaddress(txtA_address.getText());
        c.setMno(txt_mno.getText());
        c.setEmpmail(txt_mail.getText());
        c.setSdate(((JTextField) dc_startdate.getDateEditor().getUiComponent()).getText());
        c.setEmpdepartment(txt_dptn.getText());
        c.setEmpdesignation(txt_dsgn.getText());
        c.setUserName(txt_usrnme.getText());
        c.setPassword(pwd_password.getPassword());
    }
    
    public static HRManagementWindow getInstance(String eID) {
        if(instance == null) {
            instance = new HRManagementWindow(eID);
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel28 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_empID = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_address = new javax.swing.JTextArea();
        txt_mno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_dptn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_dsgn = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dc_startdate = new com.toedter.calendar.JDateChooser();
        dc_birth = new com.toedter.calendar.JDateChooser();
        lbl_eid = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        cmb_empgender = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_usrnme = new javax.swing.JTextField();
        pwd_password = new javax.swing.JPasswordField();
        jPanel22 = new javax.swing.JPanel();
        Addbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_employee = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        btn_empSearch = new javax.swing.JButton();
        txt_empSearch = new javax.swing.JTextField();
        btn_viewallemp = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        cmb_empSearch = new javax.swing.JComboBox<>();
        lbl_SearchValidate = new javax.swing.JLabel();
        lbl_btntblvalidate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel25 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_candidate = new javax.swing.JTable();
        Combobox_search = new javax.swing.JComboBox<>();
        candidate_text = new javax.swing.JTextField();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        txt_interID = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jButton41 = new javax.swing.JButton();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        lbl_iidVal = new javax.swing.JLabel();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jTextField45 = new javax.swing.JTextField();
        jButton42 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tbl_interview_schedule = new javax.swing.JTable();
        jButton49 = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_attendance = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField23 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField26 = new javax.swing.JTextField();
        jButton28 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton34 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField35 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_job = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR Management");
        setMinimumSize(new java.awt.Dimension(970, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel28.setBackground(new java.awt.Color(0, 20, 60));
        jPanel28.setToolTipText("");
        jPanel28.setMinimumSize(new java.awt.Dimension(970, 660));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("HR Management");
        jPanel28.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel28.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 50, 40));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel28.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, 39));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(28, 48, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(28, 48, 90));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add / Edit Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(28, 48, 90));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(28, 48, 90));
        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee ID        :");
        jPanel19.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name            :");
        jPanel19.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIC                     :");
        jPanel19.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender               :");
        jPanel19.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth       :");
        jPanel19.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        txt_empID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_empID.setToolTipText("");
        txt_empID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empIDActionPerformed(evt);
            }
        });
        jPanel19.add(txt_empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, -1));

        txt_nic.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel19.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address              :");
        jPanel19.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtA_address.setColumns(20);
        txtA_address.setRows(5);
        jScrollPane1.setViewportView(txtA_address);

        jPanel19.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, 40));

        txt_mno.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel19.add(txt_mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mobile Number   :");
        jPanel19.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        txt_mail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_mailMouseExited(evt);
            }
        });
        jPanel19.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 130, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email                  :");
        jPanel19.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Department        :");
        jPanel19.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        txt_dptn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel19.add(txt_dptn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 130, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Designation        :");
        jPanel19.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        txt_dsgn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_dsgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dsgnActionPerformed(evt);
            }
        });
        jPanel19.add(txt_dsgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 130, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Start Date          :");
        jPanel19.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));
        jPanel19.add(dc_startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 130, -1));
        jPanel19.add(dc_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 130, -1));
        jPanel19.add(lbl_eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 20));

        txt_fname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_fname.setToolTipText("");
        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        jPanel19.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, -1));

        cmb_empgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        jPanel19.add(cmb_empgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, 20));

        jPanel6.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 240));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 260));

        jPanel8.setBackground(new java.awt.Color(28, 48, 90));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Login Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(28, 48, 90));
        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username           :");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Password            :");

        txt_usrnme.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_usrnme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usrnmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_usrnme, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(pwd_password))
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_usrnme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pwd_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 80));

        jPanel22.setBackground(new java.awt.Color(0, 0, 102));
        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -110, 300, 110));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 330, 110));

        Addbutton.setBackground(new java.awt.Color(0, 102, 0));
        Addbutton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Addbutton.setText("Add");
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });
        jPanel5.add(Addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 80, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, -1, -1));

        updateButton.setBackground(new java.awt.Color(0, 102, 255));
        updateButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel5.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 960, -1));

        jPanel10.setBackground(new java.awt.Color(28, 48, 90));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee_Id", "Full_name", "Name_with_initials", "Gender", "NIC", "DoB", "Address", "Home_No", "Mobile_No", "email", "Department", "Designation", "start_date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_employee);
        if (tbl_employee.getColumnModel().getColumnCount() > 0) {
            tbl_employee.getColumnModel().getColumn(3).setHeaderValue("JobName");
            tbl_employee.getColumnModel().getColumn(4).setHeaderValue("Type");
            tbl_employee.getColumnModel().getColumn(5).setHeaderValue("Date");
            tbl_employee.getColumnModel().getColumn(6).setHeaderValue("Time");
            tbl_employee.getColumnModel().getColumn(7).setHeaderValue("Interviewer");
            tbl_employee.getColumnModel().getColumn(8).setHeaderValue("Status");
            tbl_employee.getColumnModel().getColumn(9).setHeaderValue("email");
            tbl_employee.getColumnModel().getColumn(10).setHeaderValue("Department");
            tbl_employee.getColumnModel().getColumn(11).setHeaderValue("Designation");
            tbl_employee.getColumnModel().getColumn(12).setHeaderValue("start_date");
        }

        jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 910, 100));

        jPanel23.setBackground(new java.awt.Color(28, 48, 90));
        jPanel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_empSearch.setBackground(new java.awt.Color(153, 153, 153));
        btn_empSearch.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_empSearch.setText("Search");
        btn_empSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empSearchActionPerformed(evt);
            }
        });
        jPanel23.add(btn_empSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 13, -1, -1));

        txt_empSearch.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel23.add(txt_empSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 14, 100, -1));

        btn_viewallemp.setBackground(new java.awt.Color(204, 204, 204));
        btn_viewallemp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_viewallemp.setText("View All Employees");
        btn_viewallemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewallempActionPerformed(evt);
            }
        });
        jPanel23.add(btn_viewallemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 13, -1, -1));

        btn_remove.setBackground(new java.awt.Color(102, 0, 0));
        btn_remove.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btn_remove.setText("Remove Employee");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel23.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 13, -1, -1));

        cmb_empSearch.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmb_empSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by", "Search by ID", "Search by Name" }));
        cmb_empSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_empSearchItemStateChanged(evt);
            }
        });
        jPanel23.add(cmb_empSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 14, 130, -1));
        jPanel23.add(lbl_SearchValidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 14, 100, 20));

        jPanel10.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 930, 160));

        lbl_btntblvalidate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(lbl_btntblvalidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 360, 20));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 960, 220));

        jTabbedPane1.addTab("Employee", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setBackground(new java.awt.Color(28, 48, 90));
        jTabbedPane3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jPanel25.setBackground(new java.awt.Color(28, 48, 90));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(28, 48, 90));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Candidate Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton36.setBackground(new java.awt.Color(0, 102, 0));
        jButton36.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton36.setText("Add Candidates");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 150, -1));

        jButton37.setBackground(new java.awt.Color(102, 0, 0));
        jButton37.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton37.setText("Remove Candidates");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jPanel27.setBackground(new java.awt.Color(28, 48, 90));
        jPanel27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_candidate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Candidate_Id", "Full_name", "Name_with_initials", "Gender", "NIC", "DoB", "Address", "Home_No", "Mobile_No", "email", "Department", "Designation", "Qualification", "Degree", "Experience"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tbl_candidate);

        jPanel27.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 890, 170));

        Combobox_search.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Combobox_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by", "Employee Id", "Employee Name" }));
        jPanel27.add(Combobox_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, -1));

        candidate_text.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel27.add(candidate_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, -1));

        jButton31.setBackground(new java.awt.Color(153, 153, 153));
        jButton31.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton31.setText("Search");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jButton32.setBackground(new java.awt.Color(204, 204, 204));
        jButton32.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton32.setText("View All Candidates");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jButton38.setBackground(new java.awt.Color(51, 153, 255));
        jButton38.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton38.setText("New Interview");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, -1, -1));

        jPanel11.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 920, 390));

        jPanel25.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 440));

        jTabbedPane3.addTab("Candidate", jPanel25);

        jPanel29.setBackground(new java.awt.Color(28, 48, 90));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel30.setBackground(new java.awt.Color(28, 48, 90));
        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Interview Schedule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_interID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel30.add(txt_interID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, -1));

        jPanel31.setBackground(new java.awt.Color(28, 48, 90));
        jPanel31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setBackground(new java.awt.Color(28, 48, 90));
        jLabel37.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Candidate Name   :");
        jPanel31.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, -1, -1));

        jLabel38.setBackground(new java.awt.Color(28, 48, 90));
        jLabel38.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Interview ID          :");
        jPanel31.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        jLabel33.setBackground(new java.awt.Color(28, 48, 90));
        jLabel33.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Job Name              :");
        jPanel31.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextField41.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel31.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 168, -1));

        jLabel34.setBackground(new java.awt.Color(28, 48, 90));
        jLabel34.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Interview Type       :");
        jPanel31.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jTextField42.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel31.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 168, -1));

        jTextField40.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel31.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 168, -1));

        jLabel35.setBackground(new java.awt.Color(28, 48, 90));
        jLabel35.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Date                       :");
        jPanel31.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel36.setBackground(new java.awt.Color(28, 48, 90));
        jLabel36.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Start Time              :");
        jPanel31.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jTextField44.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel31.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 168, -1));

        jButton41.setBackground(new java.awt.Color(153, 153, 153));
        jButton41.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton41.setText("Reset");
        jPanel31.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 180, -1));
        jPanel31.add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 170, -1));
        jPanel31.add(lbl_iidVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 20));

        jButton47.setBackground(new java.awt.Color(0, 102, 0));
        jButton47.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton47.setText("Add  Interview Schedule");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel31.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jButton48.setBackground(new java.awt.Color(0, 102, 255));
        jButton48.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton48.setText("Update Schedule");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel31.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 180, -1));

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 900, 140));

        jPanel29.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 930, 170));

        jPanel32.setBackground(new java.awt.Color(28, 48, 90));
        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Interview Schedules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by", "Employee Id", "Employee Name" }));
        jPanel32.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, -1));

        jTextField45.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel32.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 100, -1));

        jButton42.setBackground(new java.awt.Color(153, 153, 153));
        jButton42.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton42.setText("Search");
        jPanel32.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jButton45.setBackground(new java.awt.Color(204, 204, 204));
        jButton45.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton45.setText("View All Schedules");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel32.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        tbl_interview_schedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Interview Id", "CID", "CName", "JobName", "Type", "Date", "Time", "Interviewer", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tbl_interview_schedule);
        if (tbl_interview_schedule.getColumnModel().getColumnCount() > 0) {
            tbl_interview_schedule.getColumnModel().getColumn(3).setHeaderValue("JobName");
            tbl_interview_schedule.getColumnModel().getColumn(4).setHeaderValue("Type");
            tbl_interview_schedule.getColumnModel().getColumn(5).setHeaderValue("Date");
            tbl_interview_schedule.getColumnModel().getColumn(6).setHeaderValue("Time");
            tbl_interview_schedule.getColumnModel().getColumn(7).setHeaderValue("Interviewer");
            tbl_interview_schedule.getColumnModel().getColumn(8).setHeaderValue("Status");
        }

        jPanel32.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 870, 150));

        jButton49.setBackground(new java.awt.Color(102, 0, 0));
        jButton49.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton49.setText("Remove Schedule");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel32.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));

        jPanel34.setBackground(new java.awt.Color(28, 48, 90));
        jPanel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        jPanel32.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 910, 240));

        jPanel29.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 930, 270));

        jTabbedPane3.addTab("Interview Schedule", jPanel29);

        jPanel2.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 510));

        jTabbedPane1.addTab("Interview & Candidate", jPanel2);

        jPanel3.setBackground(new java.awt.Color(28, 48, 90));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(28, 48, 90));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Attendence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton26.setBackground(new java.awt.Color(0, 102, 255));
        jButton26.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton26.setText("Attendance Report");
        jPanel15.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 170, -1));

        jButton27.setBackground(new java.awt.Color(102, 0, 0));
        jButton27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton27.setText("Delete");
        jPanel15.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        jPanel13.setBackground(new java.awt.Color(28, 48, 90));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl_attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AttendanceId", "EmpId", "EName", "Date", "Attend", "Attended_Time", "Leave_Time", "Att_Type", "working_hrs", "ot_hrs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbl_attendance);

        jComboBox4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by", "Today's Attendance", "All Attendance" }));

        jTextField23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jButton25.setBackground(new java.awt.Color(153, 153, 153));
        jButton25.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton25.setText("Search");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton25)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 580, 450));

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 600, 480));

        jPanel16.setBackground(new java.awt.Color(28, 48, 90));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Record Attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by", "Employee Id", "Employee Name" }));
        jPanel16.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        jTextField26.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel16.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, -1));

        jButton28.setBackground(new java.awt.Color(153, 153, 153));
        jButton28.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton28.setText("Search");
        jPanel16.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Id", "Full Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable5);

        jPanel16.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 160));

        jButton34.setBackground(new java.awt.Color(153, 153, 153));
        jButton34.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton34.setText("Refresh");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 80, -1));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Employee ID          :");
        jPanel16.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Full Name               :");
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jTextField27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel16.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 130, -1));

        jTextField28.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel16.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 130, -1));

        jButton29.setBackground(new java.awt.Color(0, 102, 0));
        jButton29.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton29.setText("Add");
        jPanel16.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 90, -1));

        jButton30.setBackground(new java.awt.Color(153, 153, 153));
        jButton30.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton30.setText("Cancel");
        jPanel16.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jPanel12.setBackground(new java.awt.Color(28, 48, 90));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 450));

        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 480));

        jTabbedPane1.addTab("Attendance", jPanel3);

        jPanel4.setBackground(new java.awt.Color(28, 48, 90));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(28, 48, 90));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add/Update Job Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Job Id                    :");
        jPanel17.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 40, -1, -1));

        jTextField24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel17.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 37, 130, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Department Id      :");
        jPanel17.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 80, -1, -1));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Job Name             :");
        jPanel17.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 120, -1, -1));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Max No. of Jobs      :");
        jPanel17.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Available                 :");
        jPanel17.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("HalfDay(Rs.)            :");
        jPanel17.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jTextField25.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel17.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 77, 130, -1));

        jTextField29.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel17.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 117, 130, -1));

        jTextField30.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel17.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 120, -1));

        jTextField31.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel17.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 120, -1));

        jTextField32.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel17.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 120, -1));

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Basic Salary(Rs.)     :");
        jPanel17.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("OverTime/h(Rs.)      :");
        jPanel17.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jTextField33.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel17.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 110, -1));

        jTextField34.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel17.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 110, -1));

        jButton18.setBackground(new java.awt.Color(0, 102, 0));
        jButton18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton18.setText("Add");
        jPanel17.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 90, -1));

        jButton19.setBackground(new java.awt.Color(0, 102, 255));
        jButton19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton19.setText("Update");
        jPanel17.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, -1));

        jButton20.setBackground(new java.awt.Color(153, 153, 153));
        jButton20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton20.setText("Reset");
        jPanel17.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));

        jPanel14.setBackground(new java.awt.Color(28, 48, 90));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 910, 180));

        jPanel4.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 930, 210));

        jPanel18.setBackground(new java.awt.Color(28, 48, 90));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Job Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by", "Job Id", "Job Name" }));
        jPanel18.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, -1));

        jTextField35.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel18.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, -1));

        jButton21.setBackground(new java.awt.Color(153, 153, 153));
        jButton21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton21.setText("Search");
        jPanel18.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jButton22.setBackground(new java.awt.Color(204, 204, 204));
        jButton22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton22.setText("View All Jobs");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        tbl_job.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Id", "Department Id", "Job Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tbl_job);

        jPanel18.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 870, 160));

        jPanel26.setBackground(new java.awt.Color(28, 48, 90));
        jPanel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 910, 240));

        jPanel4.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 930, 270));

        jTabbedPane1.addTab("Job Analysis", jPanel4);

        jPanel28.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 970, 560));

        getContentPane().add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 620));
        jPanel28.getAccessibleContext().setAccessibleName("HR Management");

        getAccessibleContext().setAccessibleName("HR Management");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewallempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewallempActionPerformed
        // TODO add your handling code here:
        HRController.loadTable(tbl_employee, "employee", "Emp_ID");
    }//GEN-LAST:event_btn_viewallempActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        MainWindow.getInstance(curEID).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:MainWindow
        dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed
       
    private void txt_empIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empIDActionPerformed
        // TODO add your handling code here:
        txt_empID.setToolTipText("gshsfh");
    }//GEN-LAST:event_txt_empIDActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        hrm.Remove(tbl_employee, lbl_btntblvalidate, "employee", "Emp_ID");
        HRController.loadTable(tbl_employee, "employee", "Emp_ID");
    }//GEN-LAST:event_btn_removeActionPerformed

    private void txt_dsgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dsgnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dsgnActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        HRController.loadTable(tbl_candidate, "candidate", "candidateID");
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        dispose();
        AddEditCandidate ae = new AddEditCandidate("");
        ae.setVisible(true);
        
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton49ActionPerformed

    private void txt_usrnmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usrnmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usrnmeActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
        // TODO add your handling code here:
        this.setEmployee();
        try {
            //insert data to database
            boolean status = HRController.InsertEmployee(c.getEmpID(),c.getFname(),c.getEmpgender(),c.getEmpnic(),
                    c.getEmpdob(),c.getEmpaddress(),c.getMno(),c.getEmpmail(),c.getEmpdepartment(),c.getEmpdesignation(),c.getSdate(),
                    c.getUserName(),c.getPassword().toString());
            if (status == true) {
                JOptionPane.showMessageDialog(null, "Employee Record Saved Successfully");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Employee Record cant save");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Can't save record..Check fields and try again");
        }
                                           
            
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void btn_empSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empSearchActionPerformed
        // TODO add your handling code here:
             String select = cmb_empSearch.getSelectedItem().toString();
        if (select.equals("Search by ID")) {
            sql = "select * from employee where Emp_ID LIKE '" + txt_empSearch.getText() + "%'";
            hrm.Search(tbl_employee, txt_empSearch, lbl_SearchValidate, sql, "", "Emp_ID");
        } else if (select.equals("Search by Name")) {
            sql = "select * from employee where full_name LIKE '" + txt_empSearch.getText() + "%'";
            hrm.Search(tbl_employee, txt_empSearch, lbl_SearchValidate, sql, "", "full_name");
        }
    }//GEN-LAST:event_btn_empSearchActionPerformed

    private void cmb_empSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_empSearchItemStateChanged
        // TODO add your handling code here:
             String select = cmb_empSearch.getSelectedItem().toString();
        if (select.equals("Search by ID")) {
            txt_empSearch.setText("Employee ID");
            Color grayColor = new Color(153, 153, 153);
            txt_empSearch.setForeground(grayColor);
        } else if (select.equals("Search by Name")) {
            txt_empSearch.setText("Employee Name");
            Color grayColor = new Color(153, 153, 153);
            txt_empSearch.setForeground(grayColor);
        }
    }//GEN-LAST:event_cmb_empSearchItemStateChanged

    private void txt_mailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mailMouseExited
        // TODO add your handling code here:
        boolean status = Validation.emailValidate(txt_mail.getText());
        
        if(status == true) {
            lbl_btntblvalidate.setText( "Valid Email Address");
        } else {
           lbl_btntblvalidate.setText("Invalid Email Address");
        }
    }//GEN-LAST:event_txt_mailMouseExited

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
         this.setEmployee();
        try {
            //insert data to database
            boolean status = HRController.UpdateEmployee(c.getEmpID(),c.getFname(),c.getEmpgender(),c.getEmpnic(),
                    c.getEmpdob(),c.getEmpaddress(),c.getMno(),c.getEmpmail(),c.getEmpdepartment(),c.getEmpdesignation(),c.getSdate(),
                    c.getUserName(),c.getPassword().toString());
            if (status == true) {
                JOptionPane.showMessageDialog(null, "Employee Record Saved Successfully");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Employee Record cant save");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Can't save record..Check fields and try again");
        }
           
        
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.txt_empID.setText("");
        this.txt_fname.setText("");
	this.cmb_empgender.setSelectedItem("");
	this.txt_nic.setText("");
	//String dob = ((JTextField) dc_birth.getDateEditor().getUiComponent()).setText("");
	this.txtA_address.setText("");
	this.txt_mno.setText("");
	this.txt_mail.setText("");
	//String sdate = ((JTextField) dc_startdate.getDateEditor().getUiComponent()).getText();
	this.txt_dptn.setText("");
	this.txt_dsgn.setText("");
	this.txt_usrnme.setText("");
	this.pwd_password.setName("");
			
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        HRController hm1 = new HRController();
        String select = Combobox_search.getSelectedItem().toString();
        if (select.equals("Search by ID")) {
            sql = "select * from candidate where candidateID LIKE '" + candidate_text.getText() + "%'";
            hm1.Search(tbl_candidate, candidate_text, lbl_SearchValidate, sql, "", "Candidate ID");
        } else if (select.equals("Search by Name")) {
            sql = "select * from candidate where full_name LIKE '" + candidate_text.getText() + "%'";
            hm1.Search(tbl_candidate, candidate_text, lbl_SearchValidate, sql, "", "Candidate Name");
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        HRController hm = new HRController();
        hm.Remove(tbl_candidate, lbl_btntblvalidate, "candidate", "candidateID");
        HRController.loadTable(tbl_candidate, "candidate", "candidateID");
    }//GEN-LAST:event_jButton37ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManagementWindow("").setVisible(true);
            }
        });
        
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JComboBox<String> Combobox_search;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btn_empSearch;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_viewallemp;
    private javax.swing.JTextField candidate_text;
    private javax.swing.JComboBox<String> cmb_empSearch;
    private javax.swing.JComboBox<String> cmb_empgender;
    public com.toedter.calendar.JDateChooser dc_birth;
    public com.toedter.calendar.JDateChooser dc_startdate;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JLabel lbl_SearchValidate;
    private javax.swing.JLabel lbl_btntblvalidate;
    private javax.swing.JLabel lbl_eid;
    private javax.swing.JLabel lbl_iidVal;
    private javax.swing.JPasswordField pwd_password;
    private javax.swing.JTable tbl_attendance;
    private javax.swing.JTable tbl_candidate;
    private javax.swing.JTable tbl_employee;
    private javax.swing.JTable tbl_interview_schedule;
    private javax.swing.JTable tbl_job;
    public javax.swing.JTextArea txtA_address;
    public javax.swing.JTextField txt_dptn;
    public javax.swing.JTextField txt_dsgn;
    public javax.swing.JTextField txt_empID;
    private javax.swing.JTextField txt_empSearch;
    public javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_interID;
    public javax.swing.JTextField txt_mail;
    public javax.swing.JTextField txt_mno;
    public javax.swing.JTextField txt_nic;
    public javax.swing.JTextField txt_usrnme;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
