/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beverage_Interface;

import HMS_Database.MyDBConnection;
import HMS_Home.MHome;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Prabas Gayadeeptha
 * 
 * @author Isira Seneviratne (19440268)
 */
public class Invoice extends javax.swing.JInternalFrame {
    /**
     * Creates new form Invoice
     */
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rst = null;

    private final Color entered = new Color(104,109,213), exited = new Color(153,204,255);
    
    public Invoice() {
        initComponents();
        conn =  MyDBConnection.connectDB();
        tableLoad(tab1, "SELECT * FROM invoice01");
        tableLoad(tab1, "SELECT inId,Bname,tibrand,qphone,bpay,brprice from invoice01"); //previously updateTable()
    }

    //table load
    private void tableLoad(JTable table, String query) {
        try {
            pst = conn.prepareStatement(query);
            rst = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while loading the table with the required data.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        aa = new javax.swing.JLabel();
        ab = new javax.swing.JLabel();
        ac = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        ae = new javax.swing.JLabel();
        af = new javax.swing.JLabel();
        txtInvoiceNo = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        inpDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Ad2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        searchbo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        cal_table = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emp_background = new javax.swing.JLabel();
        PnlMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblBarStock = new javax.swing.JLabel();
        lblMainStock = new javax.swing.JLabel();
        lblBevOrders = new javax.swing.JLabel();
        lblSoftDrinkStock = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 0, 204)));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aa.setText("Invoice No");
        jPanel2.add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        ab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ab.setText("Date");
        jPanel2.add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        ac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ac.setText("Time");
        jPanel2.add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        ad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ad.setText("Quantity");
        jPanel2.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        ae.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ae.setText("Brand");
        jPanel2.add(ae, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        af.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        af.setText("Price");
        jPanel2.add(af, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 50, 20));

        txtInvoiceNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInvoiceNoKeyTyped(evt);
            }
        });
        jPanel2.add(txtInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 160, 30));

        txtTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimeKeyTyped(evt);
            }
        });
        jPanel2.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 163, 30));

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });
        jPanel2.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 163, 30));
        jPanel2.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 163, 30));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 163, 30));

        inpDate.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(inpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 374, 520));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 148, 139), 3));

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice No.", "Date", "Time", "Quantity", "Brand", "Price", "Amount"
            }
        ));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 790, 180));

        jPanel4.setBackground(new java.awt.Color(0, 183, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(51, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 11, 133, 52));

        Ad2.setBackground(new java.awt.Color(0, 153, 0));
        Ad2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Ad2.setForeground(new java.awt.Color(255, 255, 255));
        Ad2.setText("Add");
        Ad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ad2ActionPerformed(evt);
            }
        });
        jPanel4.add(Ad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 133, 52));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 11, 127, 52));
        jPanel4.add(searchbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, 30));

        jButton1.setForeground(new java.awt.Color(51, 51, 0));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 133, 30));

        jButton5.setBackground(new java.awt.Color(255, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 11, 123, 52));

        jButton9.setText("Home");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jButton10.setText("Beverage Home");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));
        jPanel4.add(cal_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 180, 30));

        jButton4.setText("Calculation");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 123, 130, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 790, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/cheap-specialty-wine.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 980, 200));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Invoice");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel1.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 174, 238));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Invoice");
        jLabel2.setOpaque(true);
        PnlMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 210, 30));

        lblBarStock.setBackground(new java.awt.Color(153, 204, 255));
        lblBarStock.setForeground(new java.awt.Color(255, 255, 255));
        lblBarStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarStock.setText("Bar Stock");
        lblBarStock.setToolTipText("Click to switch to the bar stock section.");
        lblBarStock.setOpaque(true);
        lblBarStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarStockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBarStockMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBarStockMouseEntered(evt);
            }
        });
        PnlMenu.add(lblBarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 30));

        lblMainStock.setBackground(new java.awt.Color(153, 204, 255));
        lblMainStock.setForeground(new java.awt.Color(255, 255, 255));
        lblMainStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainStock.setText("Main Stock Management");
        lblMainStock.setToolTipText("Click to switch to the main stock management section.");
        lblMainStock.setOpaque(true);
        lblMainStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainStockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMainStockMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMainStockMouseEntered(evt);
            }
        });
        PnlMenu.add(lblMainStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 210, 30));

        lblBevOrders.setBackground(new java.awt.Color(153, 204, 255));
        lblBevOrders.setForeground(new java.awt.Color(255, 255, 255));
        lblBevOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBevOrders.setText("Beverage Orders");
        lblBevOrders.setToolTipText("Click to switch to the beverage orders section.");
        lblBevOrders.setOpaque(true);
        lblBevOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseEntered(evt);
            }
        });
        PnlMenu.add(lblBevOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 210, 30));

        lblSoftDrinkStock.setBackground(new java.awt.Color(153, 204, 255));
        lblSoftDrinkStock.setForeground(new java.awt.Color(255, 255, 255));
        lblSoftDrinkStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoftDrinkStock.setText("Soft Drink Stock");
        lblSoftDrinkStock.setToolTipText("Click to switch to the soft drink stock section.");
        lblSoftDrinkStock.setOpaque(true);
        lblSoftDrinkStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoftDrinkStockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSoftDrinkStockMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSoftDrinkStockMouseEntered(evt);
            }
        });
        PnlMenu.add(lblSoftDrinkStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 210, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/MenuBar_Back_Beverage.jpg"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //update button here
        try {
            String value1 = txtInvoiceNo.getText();
            String value2 = ((JTextField) inpDate.getDateEditor().getUiComponent()).getText();
            String value3 = txtTime.getText();
            String value4 = txtQty.getText();
            String value5 = txtBrand.getText();
            String value6 = txtPrice.getText();
            //inId,Bname,tibrand,qphone,bpay,brprice
            String sql = "update invoice01 set Bname='" + value2 + "',tibrand='" + value3 + "',qphone='" + value4 + "',bpay='" + value5 + "',brprice='" + value6 + "' where inId = '" + value1 + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Updated");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tableLoad(tab1, "SELECT inId,Bname,tibrand,qphone,bpay,brprice from invoice01");
        /*

        try{

            String value1= Invo.getText();
            String value2= hh.getText();
            String value3= ss.getText();
            String value4= ((JTextField)hj.getDateEditor().getUiComponent()).getText();
            String value5= as.getText();
            String value6= zx.getText();

            String q= "update invoice01 set inId='"+value1+"',Bname='"+value2+"',tibrand='"+value3+"',qphone='"+value4+"',bpay='"+value5+"',brprice='"+value6+,"'";
            pst= conn .prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Record Updated");
        }
        catch (Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        updateTable();

        }

         */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Ad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ad2ActionPerformed
        try {
            if (txtInvoiceNo.getText().isEmpty()
                    || ((JTextField)inpDate.getDateEditor().getUiComponent()).getText().isEmpty()
                    || txtTime.getText().isEmpty()
                    || txtQty.getText().isEmpty()
                    || txtBrand.getText().isEmpty()
                    || txtPrice.getText().isEmpty())              
            {
                JOptionPane.showMessageDialog(null, "Some data has not been entered. Enter missing data.", "Missing Data",
                        JOptionPane.ERROR_MESSAGE);
            }
            else {
                pst = conn.prepareStatement("INSERT INTO invoice01 (inId,Bname,tibrand,qphone,bpay,brprice)"
                        + " values (?,?,?,?,?,?)");

                pst.setString(1, txtInvoiceNo.getText());
                pst.setString(2, ((JTextField) inpDate.getDateEditor().getUiComponent()).getText());
                pst.setString(3, txtTime.getText());
                pst.setString(4, txtQty.getText());
                pst.setString(5, txtBrand.getText());
                pst.setString(6, txtPrice.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null, "Record inserted successfully.", "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                tableLoad(tab1, "SELECT * FROM invoice01");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while inserting the record.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        //Invo.setText(null);
        //hh.setDate(null);
        //ss.setText(null);
        //hj.setText(null);
        //as.setText(null);
        //zx.setText(null);
    }//GEN-LAST:event_Ad2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BeverageHome e1 = new BeverageHome();
        getDesktopPane().add(e1).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //Search button in here
        /*   String inId = searchbo.getText();
        String q = "SELECT inId,Bname,tibrand,qphone,bpay,brprice from invoice1 where ename LIKE '%"+inId+"%'";

        try{
            pst = conn.prepareStatement(q);
            rst = pst.executeQuery();
            tab1.setModel(DbUtils.resultSetToTableModel(rst));
        }

        catch(Exception e){

            System.out.println(e);

        }        //Search button in here
         */
        try {
            pst = conn.prepareStatement("select * from invoice01 where inId=?");
            pst.setString(1, searchbo.getText());
            rst = pst.executeQuery();                            // inId,Bname,tibrand,qphone,bpay,brprice
            if (rst.next()) {
                String add1 = rst.getString("inId");//((JTextField)date_search().getUiComponent()).getText();
                txtInvoiceNo.setText(add1);
                // ((JTextField).getUiComponent()).getText();
                // String add2 = rst.JDateChooser("Bname");
                //hh.JDateChooser(add2);
                String add3 = rst.getString("tibrand");
                txtTime.setText(add3);
                
                String add4 = rst.getString("qphone");
                txtQty.setText(add4);

                String add5 = rst.getString("bpay");
                txtBrand.setText(add5);

                String add6 = rst.getString("brprice");
                txtPrice.setText(add6);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while retrieving the desired invoice.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // delete record
        try {
            pst = conn.prepareStatement("delete from invoice01 where inId= ?");
            pst.setString(1, txtInvoiceNo.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record successfully deleted.", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            tableLoad(tab1, "SELECT inId,Bname,tibrand,qphone,bpay,brprice from invoice01");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while deleting the record.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MHome m = new MHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        BeverageHome m = new BeverageHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            double a = Double.parseDouble(txtQty.getText());
            double b = Double.parseDouble(txtPrice.getText());
            double am = a*b;
            cal_table.setText(""+am);
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid value input for one or both"
                    + " of the number fields. Enter a "
                    + "valid value.", "Invalid Number", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtInvoiceNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInvoiceNoKeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE
                || c == KeyEvent.VK_DELETE)) {
            evt.consume(); 
        }
    }//GEN-LAST:event_txtInvoiceNoKeyTyped

    private void txtTimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimeKeyTyped
         
    }//GEN-LAST:event_txtTimeKeyTyped

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE
                || c == KeyEvent.VK_DELETE)) {
            evt.consume(); 
        }
    }//GEN-LAST:event_txtQtyKeyTyped

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE
                || c == KeyEvent.VK_DELETE)) {
            evt.consume(); 
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        try {
            int row = tab1.getSelectedRow();
            String Table_click = tab1.getModel().getValueAt(row, 0).toString();
            pst = conn.prepareStatement("select * from invoice01 where inId='" + Table_click + "'");
            rst = pst.executeQuery();   //inId,Bname,tibrand,qphone,bpay,brprice
            while (rst.next()) {
                String add1 = rst.getString("inId");
                txtInvoiceNo.setText(add1);

                //--------------------------------------------
                String add2 = rst.getString("Bname");
                //date_dob.setDate(add4);
                //get selected date
                Date date;
                try {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(add2);
                    inpDate.setDate(date);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Unable to parse date.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                //-------------------------------------------
                String add3 = rst.getString("tibrand");
                txtTime.setText(add3);

                String add4 = rst.getString("qphone");
                txtQty.setText(add4);

                String add5 = rst.getString("bpay");
                txtBrand.setText(add5);

                String add6 = rst.getString("brprice");
                txtPrice.setText(add6);
                //-------------------------------------------
                // String add12=rs.getString("joined_date");
                //date_joined.setText(add9);

                //get selected date
                //  try {
                    //date = new SimpleDateFormat("yyyy-MM-dd").parse(add12);
                    //date_joined.setDate(date);
                    //  } catch (ParseException ex) {
                    //    }
                //-------------------------------------------
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while retrieving the record.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tab1MouseClicked

    private void lblBarStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseClicked
        getDesktopPane().add(new BarStockManagement()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBarStockMouseClicked

    private void lblBarStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseEntered
        lblBarStock.setBackground(entered);
    }//GEN-LAST:event_lblBarStockMouseEntered

    private void lblBarStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseExited
        lblBarStock.setBackground(exited);
    }//GEN-LAST:event_lblBarStockMouseExited

    private void lblBevOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseClicked
        getDesktopPane().add(new BeverageOrder()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBevOrdersMouseClicked

    private void lblBevOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseEntered
        lblBevOrders.setBackground(entered);
    }//GEN-LAST:event_lblBevOrdersMouseEntered

    private void lblBevOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseExited
        lblBevOrders.setBackground(exited);
    }//GEN-LAST:event_lblBevOrdersMouseExited

    private void lblSoftDrinkStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoftDrinkStockMouseClicked
        getDesktopPane().add(new SoftDrinkStock()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSoftDrinkStockMouseClicked

    private void lblSoftDrinkStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoftDrinkStockMouseEntered
        lblSoftDrinkStock.setBackground(entered);
    }//GEN-LAST:event_lblSoftDrinkStockMouseEntered

    private void lblSoftDrinkStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoftDrinkStockMouseExited
        lblSoftDrinkStock.setBackground(exited);
    }//GEN-LAST:event_lblSoftDrinkStockMouseExited

    private void lblMainStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainStockMouseClicked
        getDesktopPane().add(new MainStockManagement()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblMainStockMouseClicked

    private void lblMainStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainStockMouseEntered
        lblMainStock.setBackground(entered);
    }//GEN-LAST:event_lblMainStockMouseEntered

    private void lblMainStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainStockMouseExited
        lblMainStock.setBackground(exited);
    }//GEN-LAST:event_lblMainStockMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ad2;
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JLabel aa;
    private javax.swing.JLabel ab;
    private javax.swing.JLabel ac;
    private javax.swing.JLabel ad;
    private javax.swing.JLabel ae;
    private javax.swing.JLabel af;
    private javax.swing.JTextField cal_table;
    private javax.swing.JLabel emp_background;
    private com.toedter.calendar.JDateChooser inpDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBarStock;
    private javax.swing.JLabel lblBevOrders;
    private javax.swing.JLabel lblMainStock;
    private javax.swing.JLabel lblSoftDrinkStock;
    private javax.swing.JTextField searchbo;
    private javax.swing.JTable tab1;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
