/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beverage_Interface;


import HMS_Database.MyDBConnection;
import HMS_Home.MHome;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Prabas Gayadeeptha
 * 
 * @author Isira Seneviratne (19440268)
 */
public class MainStockManagement extends javax.swing.JInternalFrame {
    /**
     * Creates new form MainStockManagement
     */
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rst = null;
    
    private final Color entered = new Color(104,109,213), exited = new Color(153,204,255);
    
    public MainStockManagement() {
        initComponents();
        conn = MyDBConnection.connectDB();
        loadTable(tab1, "SELECT * FROM main1");
        //loadTable(tab1, "SELECT * FROM main22"); //previously tableLoad1();
        loadTable(tab1, "SELECT Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count from main1"); //previously updateTable();
    }
    
    private void loadTable(JTable table, String query) {
        try {
            pst = conn.prepareStatement(query);   
            rst = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rst));
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while retrieving the records.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }
    
    private void clearFields() {
        txtStockID.setText("");
        txtProdName.setText("");
        txtBrand.setText("");
        txtVolume.setText("");
        txtQty.setText("");
        txtTotCount.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtStockID = new javax.swing.JTextField();
        txtProdName = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtVolume = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtTotCount = new javax.swing.JTextField();
        tost = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        REPORT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab2 = new javax.swing.JTable();
        txtRdrug = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        PnlMenu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblSoftDrinkStock = new javax.swing.JLabel();
        lblInvoice = new javax.swing.JLabel();
        lblBevOrders = new javax.swing.JLabel();
        lblBarStock = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 570));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(51, 102, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Stock ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Product Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Brand");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Volume");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Quantity");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total Count");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total Stock");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));
        jPanel2.add(txtStockID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 144, -1));
        jPanel2.add(txtProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 145, -1));

        txtBrand.setText(" ");
        jPanel2.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 145, -1));

        txtVolume.setText(" ");
        jPanel2.add(txtVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 145, -1));

        txtQty.setText(" ");
        jPanel2.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 145, -1));

        txtTotCount.setText(" ");
        jPanel2.add(txtTotCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 145, -1));

        tost.setText(" ");
        jPanel2.add(tost, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 145, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 510));

        jPanel6.setBackground(new java.awt.Color(0, 183, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/Update-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 50));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/Accept-icon.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 140, 50));
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/View-Tender-icon.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, 50));

        jButton9.setText("Home");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        jButton10.setText("Beverage Home");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/disaprrove-icon.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 50));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, 50));

        REPORT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REPORT.setForeground(new java.awt.Color(204, 0, 0));
        REPORT.setText("REPORT");
        REPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTActionPerformed(evt);
            }
        });
        jPanel6.add(REPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 260, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 850, 130));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Main Stock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stock ID", "Product Name", "Brand", "Volume", "Quantity", "Total Count"
            }
        ));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 820, 180));

        tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stock ID", "Product Name", "Brand", "Volume", "Quantity", "Total Count"
            }
        ));
        jScrollPane3.setViewportView(tab2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 820, 140));
        jPanel1.add(txtRdrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 120, -1));

        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1250, 580));

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 174, 238));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Main Stock Management");
        jLabel9.setOpaque(true);
        PnlMenu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 210, 30));

        lblSoftDrinkStock.setBackground(new java.awt.Color(153, 204, 255));
        lblSoftDrinkStock.setForeground(new java.awt.Color(255, 255, 255));
        lblSoftDrinkStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoftDrinkStock.setText("Soft Drink Stock");
        lblSoftDrinkStock.setToolTipText("Click to switch to the soft drink stock section.");
        lblSoftDrinkStock.setOpaque(true);
        lblSoftDrinkStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoftDrinkStockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSoftDrinkStockMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSoftDrinkStockMouseEntered(evt);
            }
        });
        PnlMenu.add(lblSoftDrinkStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 210, 30));

        lblInvoice.setBackground(new java.awt.Color(153, 204, 255));
        lblInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvoice.setText("Invoice");
        lblInvoice.setToolTipText("Click to switch to the invoice section.");
        lblInvoice.setOpaque(true);
        lblInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseEntered(evt);
            }
        });
        PnlMenu.add(lblInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 210, 30));

        lblBevOrders.setBackground(new java.awt.Color(153, 204, 255));
        lblBevOrders.setForeground(new java.awt.Color(255, 255, 255));
        lblBevOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBevOrders.setText("Beverage Orders");
        lblBevOrders.setToolTipText("Click to switch to the beverage orders section.");
        lblBevOrders.setOpaque(true);
        lblBevOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseEntered(evt);
            }
        });
        PnlMenu.add(lblBevOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 210, 30));

        lblBarStock.setBackground(new java.awt.Color(153, 204, 255));
        lblBarStock.setForeground(new java.awt.Color(255, 255, 255));
        lblBarStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarStock.setText("Bar Stock");
        lblBarStock.setToolTipText("Click to switch to the bar stock section.");
        lblBarStock.setOpaque(true);
        lblBarStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarStockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBarStockMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBarStockMouseEntered(evt);
            }
        });
        PnlMenu.add(lblBarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/MenuBar_Back_Beverage.jpg"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //update table
        try {
            String value1 = txtStockID.getText();                   //Stock_Id
            //Product Name
            //Brand
            //Volume
            //Quantity
            //Total Count
            //Total Stock
            String value2 = txtProdName.getText();
            String value3 = txtBrand.getText();
            String value4 = txtVolume.getText();
            String value5 = txtQty.getText();
            String value6 = txtTotCount.getText();
           // String value7 = tost.getText();

            //inId,Bname,tibrand,qphone,bpay,brprice
            String q = "update main1 set Product Name='"+value2+"',Brand ='"+value3+"',Volume='"+value4+"',Quantity='"+value5+"',Total_Count='"+value6+"' where Stock_Id = '"+value1+"'";
            pst = conn.prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record successfully updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while updating the record.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            pst = conn.prepareStatement("INSERT INTO main1(Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count)"
                    + " values(?,?,?,?,?,?)");
            
            pst.setString(1, txtStockID.getText());
            pst.setString(2, txtProdName.getText());
            pst.setString(3, txtBrand.getText());
            pst.setString(4, txtVolume.getText());
            pst.setString(5, txtQty.getText());
            pst.setString(6, txtTotCount.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Successfully inserted new record.", "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
            loadTable(tab1, "SELECT * FROM main1");
        } catch(SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MHome m = new MHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        BeverageHome m = new BeverageHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String qty = txtRdrug.getText();
        int q = tab1.getSelectedRow();
        int newQty = Integer.parseInt(qty);
        String quantity = tab1.getValueAt(q, 5).toString();
        int oldQty = Integer.parseInt(quantity);

        if (txtRdrug.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input a quantity.", "No quantity entered", JOptionPane.ERROR_MESSAGE);
        }
        else if (newQty <= oldQty) {
            try {
                pst = conn.prepareStatement("INSERT INTO main22(Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count)"
                        + " values(?,?,?,?,?,?)");

                pst.setString(1, txtStockID.getText());
                pst.setString(2, txtProdName.getText());
                pst.setString(3, txtBrand.getText());
                pst.setString(4, txtVolume.getText());
                pst.setString(5, txtQty.getText());
                pst.setString(6, txtTotCount.getText());
             
                pst.execute();

                String value1 = txtStockID.getText();
                pst = conn.prepareStatement("UPDATE main1 SET Quantity = Quantity - " + qty
                        + " WHERE Stock_Id='" + value1 + "'");
                pst.execute();
                //tableLoad1();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "An error occurred while inserting or updating the record.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            JOptionPane.showMessageDialog(null, "The drug was issued successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            loadTable(tab1, "SELECT * FROM main1");
            loadTable(tab2, "SELECT * FROM main22");
        }
        else {
            JOptionPane.showMessageDialog(null, "The requested quantity cannot be issued.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        try {
            int row = tab1.getSelectedRow();//Stock_id,product_name,Brand,Volume,Quantity,Pay_by,Price,Amount
            String Table_click = tab1.getModel().getValueAt(row, 0).toString();
            
            pst = conn.prepareStatement("select * from main1 where Stock_id='" + Table_click + "'");
            rst = pst.executeQuery();
            while (rst.next()) {
//Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count
                String add1 = rst.getString("Stock_id");
                txtStockID.setText(add1);
                //--------------------------------------------
               /* String add2 = rst.getString("Bname");
                //date_dob.setDate(add4);
                //get selected date
                java.util.Date date;
                try {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(add2);

                    hh.setDate(date);
                } catch (ParseException ex) {

                }*/
                //-------------------------------------------
                String add2 = rst.getString("product_name");
                txtProdName.setText(add2);                          

                String add3 = rst.getString("Brand");
                txtBrand.setText(add3);

                String add4 = rst.getString("Volume");
                txtVolume.setText(add4);

                String add5 = rst.getString("Quantity");
                txtQty.setText(add5);
                
                 String add6 = rst.getString("Total_Count");
                txtTotCount.setText(add6);
                //-------------------------------------------
                // String add12=rs.getString("joined_date");
                //date_joined.setText(add9);

                //get selected date
                //  try {
                //date = new SimpleDateFormat("yyyy-MM-dd").parse(add12);
                //date_joined.setDate(date);
                //  } catch (ParseException ex) {
                //    }
                //-------------------------------------------
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while loading data.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tab1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // delete record
        try {
            pst = conn.prepareStatement("delete from main1 where Stock_id= ?");
            pst.setString(1, txtStockID.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record successfully deleted.", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while deleting the record.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        loadTable(tab1, "SELECT Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count from main1");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      /*String r;
        try{
        r= "delete from main22";
         pst = conn.prepareStatement(r);
         pst.execute();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        tableLoad1();
        // TODO add your handling code here:
      */          
    }//GEN-LAST:event_jButton6ActionPerformed

    private void REPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTActionPerformed
        try {
            JasperDesign jd = JRXmlLoader.load("D:\\SLIIT\\2nd Year\\2nd Semester\\ITP - Information Technology Project\\Project\\Hotel_Management_System(Selsan)\\MainStock.jrxml");// Path for the Report
            String sql = "SELECT * FROM main1";// User input of SQL
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
            JasperViewer.viewReport(jp);
        }
        catch (JRException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while generating the report.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_REPORTActionPerformed

    private void lblBarStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseClicked
        getDesktopPane().add(new BarStockManagement()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBarStockMouseClicked

    private void lblBevOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseClicked
        getDesktopPane().add(new BeverageOrder()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBevOrdersMouseClicked

    private void lblInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseClicked
        getDesktopPane().add(new Invoice()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblInvoiceMouseClicked

    private void lblSoftDrinkStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoftDrinkStockMouseClicked
        getDesktopPane().add(new SoftDrinkStock()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSoftDrinkStockMouseClicked

    private void lblBarStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseEntered
        lblBarStock.setBackground(entered);
    }//GEN-LAST:event_lblBarStockMouseEntered

    private void lblBarStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseExited
        lblBarStock.setBackground(exited);
    }//GEN-LAST:event_lblBarStockMouseExited

    private void lblBevOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseEntered
        lblBevOrders.setBackground(entered);
    }//GEN-LAST:event_lblBevOrdersMouseEntered

    private void lblBevOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseExited
        lblBevOrders.setBackground(exited);
    }//GEN-LAST:event_lblBevOrdersMouseExited

    private void lblInvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseEntered
        lblInvoice.setBackground(entered);
    }//GEN-LAST:event_lblInvoiceMouseEntered

    private void lblInvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseExited
        lblInvoice.setBackground(exited);
    }//GEN-LAST:event_lblInvoiceMouseExited

    private void lblSoftDrinkStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoftDrinkStockMouseEntered
        lblSoftDrinkStock.setBackground(entered);
    }//GEN-LAST:event_lblSoftDrinkStockMouseEntered

    private void lblSoftDrinkStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoftDrinkStockMouseExited
        lblSoftDrinkStock.setBackground(exited);
    }//GEN-LAST:event_lblSoftDrinkStockMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton REPORT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBarStock;
    private javax.swing.JLabel lblBevOrders;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblSoftDrinkStock;
    private javax.swing.JTable tab1;
    private javax.swing.JTable tab2;
    private javax.swing.JTextField tost;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtRdrug;
    private javax.swing.JTextField txtStockID;
    private javax.swing.JTextField txtTotCount;
    private javax.swing.JTextField txtVolume;
    // End of variables declaration//GEN-END:variables
}
