/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beverage_Interface;


import HMS_Database.MyDBConnection;
import HMS_Home.MHome;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class MainStock_Management extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainStock_Management
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    String passCID;
    public MainStock_Management() {
        initComponents();
        conn =  MyDBConnection.connectDB();
        tableLoad();
        //tableLoad1();
       // update_table();
       update_table();
    }
    private void update_table() {

        try {
            String sql = "SELECT Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count from main1 ";
            //String sql = "SELECT id,f_name,l_name,category from trainers ";
            pst = conn.prepareStatement(sql);
            rst = pst.executeQuery();

            tab1.setModel(DbUtils.resultSetToTableModel(rst));

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }
    public void tableLoad(){
        
       // Bname,tibrand,qphone,bpay,brprice
        
        try{
        
        String q = "SELECT * FROM main1 ";
         pst = conn.prepareStatement(q);   
         rst = pst.executeQuery();
         
         tab1.setModel(DbUtils.resultSetToTableModel(rst));
       
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }     
      public void clearFeilds(){
        
         st.setText("");
        pr.setText("");
        br.setText("");
        vo.setText("");
         qu.setText("");
         to.setText("");
        
      } 
        
//table load 2
     public void tableLoad1(){
        
       // Bname,tibrand,qphone,bpay,brprice
        
        try{
        
        String q = "SELECT * FROM main22 ";
         pst = conn.prepareStatement(q);   
         rst = pst.executeQuery();
         
         tab2.setModel(DbUtils.resultSetToTableModel(rst));
       
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        st = new javax.swing.JTextField();
        pr = new javax.swing.JTextField();
        br = new javax.swing.JTextField();
        vo = new javax.swing.JTextField();
        qu = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        tost = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        REPORT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab2 = new javax.swing.JTable();
        Rdrug = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        PnlMenu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 570));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(51, 102, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Stock ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Product Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Brand");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Volume");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Quantity");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total Count");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total Stock");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        jPanel2.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 144, -1));
        jPanel2.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 145, -1));

        br.setText(" ");
        jPanel2.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 145, -1));

        vo.setText(" ");
        jPanel2.add(vo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 145, -1));

        qu.setText(" ");
        jPanel2.add(qu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 145, -1));

        to.setText(" ");
        jPanel2.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 145, -1));

        tost.setText(" ");
        jPanel2.add(tost, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 145, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 510));

        jPanel6.setBackground(new java.awt.Color(0, 183, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/Update-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 50));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/Accept-icon.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 140, 50));
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/View-Tender-icon.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, 50));

        jButton9.setText("Home");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        jButton10.setText("Beverage Home");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/disaprrove-icon.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 50));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, 50));

        REPORT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REPORT.setForeground(new java.awt.Color(204, 0, 0));
        REPORT.setText("REPORT");
        REPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTActionPerformed(evt);
            }
        });
        jPanel6.add(REPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 260, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 850, 130));

        jLabel1.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Main Stock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stock ID", "Product Name", "Brand", "Volume", "Quantity", "Total Count"
            }
        ));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 820, 180));

        tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stock ID", "Product Name", "Brand", "Volume", "Quantity", "Total Count"
            }
        ));
        jScrollPane3.setViewportView(tab2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 820, 140));

        Rdrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdrugActionPerformed(evt);
            }
        });
        jPanel1.add(Rdrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 120, -1));

        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1250, 580));

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/MenuBar_Back_Beverage.jpg"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //update table
            try{
            String value1 = st.getText();                   //Stock_Id
            //Product Name
            //Brand
            //Volume
            //Quantity
            //Total Count
            //Total Stock
            String value2 = pr.getText();
            String value3 = br.getText();
            String value4 = vo.getText();
            String value5 = qu.getText();
            String value6 = to.getText();
           // String value7 = tost.getText();

            //inId,Bname,tibrand,qphone,bpay,brprice
            String q = "update main1 set Product Name='"+value2+"',Brand ='"+value3+"',Volume='"+value4+"',Quantity='"+value5+"',Total_Count='"+value6+"' where Stock_Id = '"+value1+"'";
            pst=conn .prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Record Updated");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        try{
            // String q = "INSERT INTO invoice01 (inId,Bname,tibrand,qphone,bpay,brprice) values (?,?,?,?,?,?)";
            String q= "INSERT INTO main1(Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count) values(?,?,?,?,?,?)";
            //System.out.println("qq");
            pst = conn.prepareStatement(q);
            pst.setString(1, st.getText());
            pst.setString(2, pr.getText());
            pst.setString(3, br.getText());
            pst.setString(4, vo.getText());
            pst.setString(5, qu.getText());
            pst.setString(6, to.getText());
            System.out.println("aa");
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Saved");
            tableLoad();

        }catch(SQLException e){

            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null ,e);
        }
        



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        MHome m = new MHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        BeverageHome m = new BeverageHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RdrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdrugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdrugActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         String qty = Rdrug.getText();

        int q = tab1.getSelectedRow();

        int newQty = Integer.parseInt(qty);

        String quantity = tab1.getValueAt(q, 5).toString();

        int oldQty = Integer.parseInt(quantity);

        // System.out.println(newQty);
        // System.out.println(oldQty);

        if (Rdrug.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Please Input Quantity", "Error", JOptionPane.ERROR_MESSAGE);

        } else if (newQty <= oldQty) {

            try {

                String r =  "INSERT INTO main22(Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count) values(?,?,?,?,?,?)";
                pst = conn.prepareStatement(r);

                pst.setString(1, st.getText());
                pst.setString(2, pr.getText());
                pst.setString(3, br.getText());
                             
                pst.setString(4, vo.getText());
                pst.setString(5, qu.getText());
                pst.setString(6, to.getText());
             
                //JOptionPane.showMessageDialog(null, "Check");
                //SysexMessage''
                System.out.print("test1");
                pst.execute();

                String value1 = st.getText();

                String sql = "UPDATE main1 SET Quantity  = Quantity - " + qty + " WHERE Stock_Id='" + value1 + "'";
                //System.out.println(sql);
                System.out.print("test2");
                pst = conn.prepareStatement(sql);
                pst.execute();
               // tableLoad1();
                
                System.out.print("test3");
            } catch (Exception e) {
                //System.out.print("test4");
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null, "Drug issued successfully");
               // tableLoad();
           // tableLoad();
            
System.out.print("test4");
        tableLoad();
        tableLoad1();
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Requested quantity cannot be issue", "Error", JOptionPane.ERROR_MESSAGE);
        }
       // tableLoad1();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
         try {
            int row = tab1.getSelectedRow();//Stock_id,product_name,Brand,Volume,Quantity,Pay_by,Price,Amount
            String Table_click = (tab1.getModel().getValueAt(row, 0).toString());
            String q = "select * from main1  where Stock_id='" + Table_click + "'";
            pst = conn.prepareStatement(q);
            rst = (ResultSet) pst.executeQuery(q);  
            while (rst.next()) {
//Stock_Id,Product_Name,Brand,Volume,Quantity,Total_Count
                String add1 = rst.getString("Stock_id");
                st.setText(add1);

                //--------------------------------------------
               /* String add2 = rst.getString("Bname");
                //date_dob.setDate(add4);
                //get selected date
                java.util.Date date;
                try {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(add2);

                    hh.setDate(date);
                } catch (ParseException ex) {

                }*/
                //-------------------------------------------
                String add2 = rst.getString("product_name");
                pr.setText(add2);                          

                String add3 = rst.getString("Brand");
                br.setText(add3);

                String add4 = rst.getString("Volume");
                vo.setText(add4);

                String add5 = rst.getString("Quantity");
                qu.setText(add5);
                
                 String add6 = rst.getString("Total_Count");
                to.setText(add6);
                
               
                //-------------------------------------------
                // String add12=rs.getString("joined_date");
                //date_joined.setText(add9);

                //get selected date
                //  try {
                //date = new SimpleDateFormat("yyyy-MM-dd").parse(add12);
                //date_joined.setDate(date);
                //  } catch (ParseException ex) {
                //    }
                //-------------------------------------------
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

                                  
                                   

    }//GEN-LAST:event_tab1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
             
           // delete record
        String q = "delete from main1 where Stock_id= ?";
        try {

            pst = conn.prepareStatement(q);

            pst.setString(1, st.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Deleted");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
        update_table();

                 
                                           

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      /*    String r;
        try{
        r= "delete from main22";
         pst = conn.prepareStatement(r);
         pst.execute();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        tableLoad1();
        // TODO add your handling code here:
      */          
    }//GEN-LAST:event_jButton6ActionPerformed

    private void REPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTActionPerformed

        try {
            JasperDesign jd = JRXmlLoader.load("D:\\SLIIT\\2nd Year\\2nd Semester\\ITP - Information Technology Project\\Project\\Hotel_Management_System(Selsan)\\MainStock.jrxml");// Path for the Report
            String sql = "SELECT * FROM main1";// USer input of SQL
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
            JasperViewer.viewReport(jp);

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_REPORTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton REPORT;
    private javax.swing.JTextField Rdrug;
    private javax.swing.JTextField br;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField qu;
    private javax.swing.JTextField st;
    private javax.swing.JTable tab1;
    private javax.swing.JTable tab2;
    private javax.swing.JTextField to;
    private javax.swing.JTextField tost;
    private javax.swing.JTextField vo;
    // End of variables declaration//GEN-END:variables

   // private void update_table() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }
}
