/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beverage_Interface;

import HMS_Database.MyDBConnection;
import HMS_Home.MHome;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class SoftDrink_Stock extends javax.swing.JInternalFrame {

    /**
     * Creates new form SoftDrink_Stock
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    String passCID;

    public SoftDrink_Stock() {
        initComponents();

        conn = MyDBConnection.connectDB();
        tableLoad();
        update_table();
    }

    private void update_table() {
        //Stock_id,Product_name,Company,Price,Quantity,ExpiryDate
        try {
            String q = "SELECT Stock_id,Product_name,Company,Price,Quantity,ExpiryDate from soft_drink";
            //String sql = "SELECT id,f_name,l_name,category from trainers ";
            pst = conn.prepareStatement(q);
            rst = pst.executeQuery();

            drinkta.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Unable to update table.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    //table load
    public void tableLoad() {

        // Bname,tibrand,qphone,bpay,brprice
        try {
            String q = "SELECT * FROM Soft_Drink ";
            pst = conn.prepareStatement(q);
            rst = pst.executeQuery();

            drinkta.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Unable to load table.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    
     public void tableLoad3()
    {
        try
        { 
            Date todatDate = new Date();
            DateFormat todayFormat= new SimpleDateFormat("yyyy-MM-dd");
            String todayDateString = todayFormat.format(todatDate);    
            String sql = "SELECT Stock_id,Product_name,Company,Price,Quantity,ExpiryDate from Soft_Drink WHERE ExpiryDate  <= '"+todayDateString+"'";
            pst = conn.prepareStatement(sql);   
            rst = pst.executeQuery();

            drinkta.setModel(DbUtils.resultSetToTableModel(rst));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Unable to load table.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     /*
      public void tableload4()
    {
        
         try{
             
           
        Date todatDate = new Date();
        DateFormat todayFormat= new SimpleDateFormat("yyyy-MM-dd");
        String todayDateString = todayFormat.format(todatDate);
        String sqls = "SELECT did,dname,dcom,dcat,dexp,dquan,dprice from drug_stock_details WHERE dexp <= '"+todayDateString+"'";
         pst = conn.prepareStatement(sqls);   
         rst = pst.executeQuery();
         
         exdrug.setModel(DbUtils.resultSetToTableModel(rst));
         
        }
        catch(Exception e)
        {
            System.out.println("Error"+e);
        }
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        as = new javax.swing.JTextField();
        ads = new javax.swing.JTextField();
        seer = new javax.swing.JTextField();
        xx = new javax.swing.JTextField();
        cccv = new javax.swing.JTextField();
        dat = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drinkta = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bb = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        REPORT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emp_background = new javax.swing.JLabel();
        PnlMenu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 51, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Stock Id");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Company");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Price");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Expiry date");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));
        jPanel2.add(as, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 137, -1));
        jPanel2.add(ads, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 137, -1));
        jPanel2.add(seer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 137, -1));
        jPanel2.add(xx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 137, -1));
        jPanel2.add(cccv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 140, -1));

        dat.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 339, 450));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 148, 139), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drinkta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stock Id", "Product Name", "Company", "Price", "Quantity", "Expiry date"
            }
        ));
        drinkta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinktaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(drinkta);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 840, 190));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 840, 200));

        jPanel5.setBackground(new java.awt.Color(0, 183, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/Accept-icon.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/Update-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, 40));

        bb.setBackground(new java.awt.Color(255, 0, 0));
        bb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bb.setForeground(new java.awt.Color(255, 255, 255));
        bb.setText("Back");
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        jPanel5.add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 70, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/View-Tender-icon.png"))); // NOI18N
        jButton4.setText("Search");
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 83, 130, 30));
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, -1));

        jButton9.setText("Home");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        jButton10.setText("Beverage Home");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        REPORT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REPORT.setForeground(new java.awt.Color(204, 0, 0));
        REPORT.setText("REPORT");
        REPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTActionPerformed(evt);
            }
        });
        jPanel5.add(REPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 160, 100));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 840, 130));

        jLabel7.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Soft ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 255));
        jLabel9.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("DRINK");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel1.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/MenuBar_Back_Beverage.jpg"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            String q = "INSERT INTO Soft_Drink (Stock_id,Product_name,Company,Price,Quantity,ExpiryDate) values (?,?,?,?,?,?)";
            pst = conn.prepareStatement(q);

            pst.setString(1, as.getText());
            pst.setString(2, ads.getText());
            pst.setString(3, seer.getText());
            pst.setString(4, cccv.getText());
            pst.setString(5, xx.getText());
            pst.setString(6, ((JTextField) dat.getDateEditor().getUiComponent()).getText());

            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Saved");
            tableLoad();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        as.setText(null);
        ads.setText(null);
        seer.setText(null);
        cccv.setText(null);
        xx.setText(null);
        dat.setDate(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //ubdate button here
        try
        {                                         //Stock_id,Product_name,Company,Price,Quantity,ExpiryDate
            String value1 = as.getText();
            String value2 = ads.getText();
            String value3 = seer.getText();
            String value4 = cccv.getText();
            String value5 = xx.getText();
            String value6 = ((JTextField) dat.getDateEditor().getUiComponent()).getText();

            String sql = "update soft_drink set Product_name='" + value2 + "',Company='" + value3 + "',Price='" + value4 + "',Quantity='" + value5 + "',ExpiryDate='" + value6 + "' where Stock_id = '" + value1 + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Updated");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        update_table();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        this.hide();
        BeverageHome g2 = new BeverageHome();
        g2.setVisible(true);
    }//GEN-LAST:event_bbActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        MHome m = new MHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        BeverageHome m = new BeverageHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void drinktaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinktaMouseClicked
        try {
            int row = drinkta.getSelectedRow();
            String Table_click = (drinkta.getModel().getValueAt(row, 0).toString());
            String q = "select * from soft_drink where Stock_id='" + Table_click + "'";
            pst = conn.prepareStatement(q);
            rst = pst.executeQuery(q);   //inId,Bname,tibrand,qphone,bpay,brprice
            while (rst.next()) {

                String add1 = rst.getString("Stock_id");    //Stock_id,Product_name,Company,Price,Quantity,ExpiryDate
                as.setText(add1);

                //--------------------------------------------
                String add2 = rst.getString("ExpiryDate");
                //date_dob.setDate(add4);
                //get selected date
                java.util.Date date;
                try
                {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(add2);
                    dat.setDate(date);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Unable to parse date.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                //-------------------------------------------
                String add3 = rst.getString("Product_name");
                ads.setText(add3);

                String add4 = rst.getString("Price");
                cccv.setText(add4);

                String add5 = rst.getString("Quantity");
                xx.setText(add5);
                  
                 String add6 = rst.getString("Company");
                seer.setText(add3);

              
                //-------------------------------------------
                // String add12=rs.getString("joined_date");
                //date_joined.setText(add9);

                //get selected date
                //  try {
                    //date = new SimpleDateFormat("yyyy-MM-dd").parse(add12);
                    //date_joined.setDate(date);
                    //  } catch (ParseException ex) {
                    //    }
                //-------------------------------------------
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
                                    

    }//GEN-LAST:event_drinktaMouseClicked

    private void REPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTActionPerformed
        try
        {
            JasperDesign jd = JRXmlLoader.load("D:\\SLIIT\\2nd Year\\2nd Semester\\ITP - Information Technology Project\\Project\\Hotel_Management_System(Selsan)\\SoftDrink.jrxml");// Path for the Report 
            String sql = "SELECT * FROM soft_drink";// USer input of SQL
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
            JasperViewer.viewReport(jp);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }

        
    }//GEN-LAST:event_REPORTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton REPORT;
    private javax.swing.JTextField ads;
    private javax.swing.JTextField as;
    private javax.swing.JButton bb;
    private javax.swing.JTextField cccv;
    private com.toedter.calendar.JDateChooser dat;
    private javax.swing.JTable drinkta;
    private javax.swing.JLabel emp_background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField seer;
    private javax.swing.JTextField xx;
    // End of variables declaration//GEN-END:variables
}
