/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beverage_Interface;

import HMS_Database.MyDBConnection;
import HMS_Home.MHome;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Prabas Gayadeeptha
 * 
 * @author Isira Seneviratne
 */
public class SoftDrinkStock extends javax.swing.JInternalFrame {
    /**
     * Creates new form SoftDrinkStock
     */
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rst = null;
    
    private final Color entered = new Color(104,109,213), exited = new Color(153,204,255);

    public SoftDrinkStock() {
        initComponents();

        conn = MyDBConnection.connectDB();
        loadTable(drinkTable, "SELECT * FROM Soft_Drink");
        loadTable(drinkTable, "SELECT Stock_id,Product_name,Company,Price,Quantity,ExpiryDate from soft_drink"); //previously updateTable()
    }

    //table load
    private void loadTable(JTable table, String query) {
        try {
            pst = conn.prepareStatement(query);
            rst = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while loading the table.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadTable_Expiry() {
        String todayDateString = new SimpleDateFormat("yyyy-MM-dd").format(new Date());    
        loadTable(drinkTable, "SELECT Stock_id,Product_name,Company,Price,Quantity,ExpiryDate"
                + " from Soft_Drink WHERE ExpiryDate <= '"+todayDateString+"'");
    }
     /*
      public void tableload4()
    {
        
         try{
             
           
        Date todatDate = new Date();
        DateFormat todayFormat= new SimpleDateFormat("yyyy-MM-dd");
        String todayDateString = todayFormat.format(todatDate);
        String sqls = "SELECT did,dname,dcom,dcat,dexp,dquan,dprice from drug_stock_details WHERE dexp <= '"+todayDateString+"'";
         pst = conn.prepareStatement(sqls);   
         rst = pst.executeQuery();
         
         exdrug.setModel(DbUtils.resultSetToTableModel(rst));
         
        }
        catch(Exception e)
        {
            System.out.println("Error"+e);
        }
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        as = new javax.swing.JTextField();
        ads = new javax.swing.JTextField();
        seer = new javax.swing.JTextField();
        xx = new javax.swing.JTextField();
        cccv = new javax.swing.JTextField();
        dat = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drinkTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bb = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        REPORT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emp_background = new javax.swing.JLabel();
        PnlMenu = new javax.swing.JPanel();
        lblMainStock = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblInvoice = new javax.swing.JLabel();
        lblBevOrders = new javax.swing.JLabel();
        lblBarStock = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 51, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Stock ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Company");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Price");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Expiry date");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));
        jPanel2.add(as, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 137, -1));
        jPanel2.add(ads, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 137, -1));
        jPanel2.add(seer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 137, -1));
        jPanel2.add(xx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 137, -1));
        jPanel2.add(cccv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 140, -1));

        dat.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 339, 450));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 148, 139), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drinkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stock ID", "Product Name", "Company", "Price", "Quantity", "Expiry date"
            }
        ));
        drinkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinkTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(drinkTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 840, 190));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 840, 200));

        jPanel5.setBackground(new java.awt.Color(0, 183, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/Accept-icon.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/Update-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, 40));

        bb.setBackground(new java.awt.Color(255, 0, 0));
        bb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bb.setForeground(new java.awt.Color(255, 255, 255));
        bb.setText("Back");
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        jPanel5.add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 70, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/View-Tender-icon.png"))); // NOI18N
        jButton4.setText("Search");
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 83, 130, 30));
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, -1));

        jButton9.setText("Home");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        jButton10.setText("Beverage Home");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        REPORT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REPORT.setForeground(new java.awt.Color(204, 0, 0));
        REPORT.setText("REPORT");
        REPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTActionPerformed(evt);
            }
        });
        jPanel5.add(REPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 160, 100));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 840, 130));

        jLabel7.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Soft ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 255));
        jLabel9.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("DRINK");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        emp_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRMS_Images/MainBackForAll.jpg"))); // NOI18N
        emp_background.setPreferredSize(new java.awt.Dimension(1190, 570));
        jPanel1.add(emp_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMainStock.setBackground(new java.awt.Color(153, 204, 255));
        lblMainStock.setForeground(new java.awt.Color(255, 255, 255));
        lblMainStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainStock.setText("Main Stock Management");
        lblMainStock.setOpaque(true);
        lblMainStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainStockMouseClicked(evt);
            }
        });
        PnlMenu.add(lblMainStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 210, 30));

        jLabel8.setBackground(new java.awt.Color(0, 174, 238));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Soft Drink Stock");
        jLabel8.setOpaque(true);
        PnlMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 210, 30));

        lblInvoice.setBackground(new java.awt.Color(153, 204, 255));
        lblInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvoice.setText("Invoice");
        lblInvoice.setOpaque(true);
        lblInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseEntered(evt);
            }
        });
        PnlMenu.add(lblInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 210, 30));

        lblBevOrders.setBackground(new java.awt.Color(153, 204, 255));
        lblBevOrders.setForeground(new java.awt.Color(255, 255, 255));
        lblBevOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBevOrders.setText("Beverage Orders");
        lblBevOrders.setOpaque(true);
        lblBevOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBevOrdersMouseEntered(evt);
            }
        });
        PnlMenu.add(lblBevOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 210, 30));

        lblBarStock.setBackground(new java.awt.Color(153, 204, 255));
        lblBarStock.setForeground(new java.awt.Color(255, 255, 255));
        lblBarStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarStock.setText("Bar Stock");
        lblBarStock.setOpaque(true);
        lblBarStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBarStockMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBarStockMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBarStockMouseEntered(evt);
            }
        });
        PnlMenu.add(lblBarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Beverage_Images/MenuBar_Back_Beverage.jpg"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel13.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String q = "INSERT INTO Soft_Drink (Stock_id,Product_name,Company,Price,Quantity,ExpiryDate) values (?,?,?,?,?,?)";
            pst = conn.prepareStatement(q);

            pst.setString(1, as.getText());
            pst.setString(2, ads.getText());
            pst.setString(3, seer.getText());
            pst.setString(4, cccv.getText());
            pst.setString(5, xx.getText());
            pst.setString(6, ((JTextField) dat.getDateEditor().getUiComponent()).getText());

            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Record inserted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadTable(drinkTable, "SELECT * FROM Soft_Drink");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while inserting the record.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        as.setText("");
        ads.setText("");
        seer.setText("");
        cccv.setText("");
        xx.setText("");
        dat.setDate(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //update button here
        try
        {                                         //Stock_id,Product_name,Company,Price,Quantity,ExpiryDate
            String value1 = as.getText();
            String value2 = ads.getText();
            String value3 = seer.getText();
            String value4 = cccv.getText();
            String value5 = xx.getText();
            String value6 = ((JTextField) dat.getDateEditor().getUiComponent()).getText();

            String sql = "update soft_drink set Product_name='" + value2 + "',Company='" + value3 + "',Price='" + value4 + "',Quantity='" + value5 + "',ExpiryDate='" + value6 + "' where Stock_id = '" + value1 + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while updating the record.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        loadTable(drinkTable, "SELECT Stock_id,Product_name,Company,Price,Quantity,ExpiryDate from soft_drink");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        BeverageHome g2 = new BeverageHome();
        getDesktopPane().add(g2).setVisible(true);
        dispose();
    }//GEN-LAST:event_bbActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MHome m = new MHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        BeverageHome m = new BeverageHome();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(m).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void drinkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinkTableMouseClicked
        try {
            int row = drinkTable.getSelectedRow();
            String Table_click = (drinkTable.getModel().getValueAt(row, 0).toString());
            String q = "select * from soft_drink where Stock_id='" + Table_click + "'";
            pst = conn.prepareStatement(q);
            rst = pst.executeQuery(q);   //inId,Bname,tibrand,qphone,bpay,brprice
            while (rst.next()) {

                String add1 = rst.getString("Stock_id");    //Stock_id,Product_name,Company,Price,Quantity,ExpiryDate
                as.setText(add1);

                //--------------------------------------------
                String add2 = rst.getString("ExpiryDate");
                //date_dob.setDate(add4);
                //get selected date
                Date date;
                try
                {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(add2);
                    dat.setDate(date);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Unable to parse date.", "Error", JOptionPane.ERROR_MESSAGE);
                    dat.setDate(null);
                }
                //-------------------------------------------
                String add3 = rst.getString("Product_name");
                ads.setText(add3);

                String add4 = rst.getString("Price");
                cccv.setText(add4);

                String add5 = rst.getString("Quantity");
                xx.setText(add5);
                  
                String add6 = rst.getString("Company");
                seer.setText(add3);

              
                //-------------------------------------------
                // String add12=rs.getString("joined_date");
                //date_joined.setText(add9);

                //get selected date
                //  try {
                    //date = new SimpleDateFormat("yyyy-MM-dd").parse(add12);
                    //date_joined.setDate(date);
                    //  } catch (ParseException ex) {
                    //    }
                //-------------------------------------------
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while retrieving the records.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_drinkTableMouseClicked

    private void REPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTActionPerformed
        try
        {
            JasperDesign jd = JRXmlLoader.load("D:\\SLIIT\\2nd Year\\2nd Semester\\ITP - Information Technology Project\\Project\\Hotel_Management_System(Selsan)\\SoftDrink.jrxml");// Path for the Report 
            String sql = "SELECT * FROM soft_drink";// USer input of SQL
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
            JasperViewer.viewReport(jp);
        } 
        catch (JRException e)
        {
            JOptionPane.showMessageDialog(null, "An error occurred while generating the report.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_REPORTActionPerformed

    private void lblBarStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseClicked
        getDesktopPane().add(new BarStockManagement()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBarStockMouseClicked

    private void lblBevOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseClicked
        getDesktopPane().add(new BeverageOrder()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBevOrdersMouseClicked

    private void lblInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseClicked
        getDesktopPane().add(new Invoice()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblInvoiceMouseClicked

    private void lblBarStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseEntered
        lblBarStock.setBackground(entered);
    }//GEN-LAST:event_lblBarStockMouseEntered

    private void lblBarStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarStockMouseExited
        lblBarStock.setBackground(exited);
    }//GEN-LAST:event_lblBarStockMouseExited

    private void lblBevOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseEntered
        lblBevOrders.setBackground(entered);
    }//GEN-LAST:event_lblBevOrdersMouseEntered

    private void lblBevOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBevOrdersMouseExited
        lblBevOrders.setBackground(exited);
    }//GEN-LAST:event_lblBevOrdersMouseExited

    private void lblInvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseEntered
        lblInvoice.setBackground(entered);
    }//GEN-LAST:event_lblInvoiceMouseEntered

    private void lblInvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseExited
        lblInvoice.setBackground(exited);
    }//GEN-LAST:event_lblInvoiceMouseExited

    private void lblMainStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainStockMouseClicked
        getDesktopPane().add(new MainStockManagement()).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblMainStockMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton REPORT;
    private javax.swing.JTextField ads;
    private javax.swing.JTextField as;
    private javax.swing.JButton bb;
    private javax.swing.JTextField cccv;
    private com.toedter.calendar.JDateChooser dat;
    private javax.swing.JTable drinkTable;
    private javax.swing.JLabel emp_background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBarStock;
    private javax.swing.JLabel lblBevOrders;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblMainStock;
    private javax.swing.JTextField seer;
    private javax.swing.JTextField xx;
    // End of variables declaration//GEN-END:variables
}
