/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transport_Interface;

import HMS_Database.MyDBConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class Drivers extends javax.swing.JInternalFrame {

    /**
     * Creates new form Drivers
     */
    Connection con = null;

    //Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Drivers() {
        initComponents();

        con = MyDBConnection.connectDB();

        tableLoad();
    }

    public void tableLoad() {
        try {

            String query = " SELECT Did,First_Name,Last_Name,Birthday,Nic,Date_of_Join,Date_of_leave,Last_Modified_date,Mobile_Number FROM driver ORDER BY Did ";

            pst = (PreparedStatement) con.prepareStatement(query);
            rs = pst.executeQuery();

            table_Driver.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMenu = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        Btn_Exit3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_Driver = new javax.swing.JTable();
        btn_deleteDriver = new javax.swing.JButton();
        btn_updateDriver = new javax.swing.JButton();
        btn_clerDriver = new javax.swing.JButton();
        btn_searchDriver = new javax.swing.JButton();
        dateOfBirth = new com.toedter.calendar.JDateChooser();
        btn_insertDriver = new javax.swing.JButton();
        dateOfJoin = new com.toedter.calendar.JDateChooser();
        dateOfLeave = new com.toedter.calendar.JDateChooser();
        dateOfLastUpdate = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbl_did = new javax.swing.JLabel();
        txt_mobileD = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Transport_Images/MenuBar_Back_Main_Transport.jpg"))); // NOI18N
        jLabel14.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel14.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel14.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DATE OF BIRTH");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, 137, 27));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("DATE OF LEAVE");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 428, 137, 27));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("LAST UPDATE DATE");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 473, 187, 29));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("FIRST NAME");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, 137, 27));

        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 255, 352, 27));

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("LAST NAME");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 292, 137, 27));

        txt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 288, 352, 27));

        jButton7.setBackground(new java.awt.Color(0, 204, 0));
        jButton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 255, -1));

        Btn_Exit3.setBackground(new java.awt.Color(255, 51, 51));
        Btn_Exit3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Exit3.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Exit3.setText("Exit");
        Btn_Exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Exit3ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 270, -1));

        table_Driver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Driver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DriverMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_Driver);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1156, 216));

        btn_deleteDriver.setBackground(new java.awt.Color(0, 0, 0));
        btn_deleteDriver.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btn_deleteDriver.setForeground(new java.awt.Color(255, 255, 0));
        btn_deleteDriver.setText("DELETE");
        btn_deleteDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteDriverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_deleteDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 530, -1));

        btn_updateDriver.setBackground(new java.awt.Color(0, 0, 0));
        btn_updateDriver.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btn_updateDriver.setForeground(new java.awt.Color(255, 255, 0));
        btn_updateDriver.setText("UPDATE");
        btn_updateDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateDriverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_updateDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 531, -1));

        btn_clerDriver.setBackground(new java.awt.Color(0, 0, 0));
        btn_clerDriver.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btn_clerDriver.setForeground(new java.awt.Color(255, 255, 0));
        btn_clerDriver.setText("CLEAR");
        btn_clerDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clerDriverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clerDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 531, -1));

        btn_searchDriver.setBackground(new java.awt.Color(0, 0, 0));
        btn_searchDriver.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btn_searchDriver.setForeground(new java.awt.Color(255, 255, 0));
        btn_searchDriver.setText("SEARCH");
        btn_searchDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchDriverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_searchDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 531, -1));

        dateOfBirth.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 321, 352, 29));

        btn_insertDriver.setBackground(new java.awt.Color(0, 0, 0));
        btn_insertDriver.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btn_insertDriver.setForeground(new java.awt.Color(255, 255, 0));
        btn_insertDriver.setText("INSERT");
        btn_insertDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertDriverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insertDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 531, -1));

        dateOfJoin.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateOfJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 391, 352, 29));

        dateOfLeave.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateOfLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 426, 352, 29));

        dateOfLastUpdate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateOfLastUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 473, 352, 29));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("MOBILE NUMBER");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 513, 137, 27));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 51, 51));
        jLabel30.setText("SEARCH BY NAME");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 190, 27));

        lbl_did.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lbl_did.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_did, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 268, -1, 27));

        txt_mobileD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mobileDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_mobileD, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 513, 352, 31));
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 358, 352, 27));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("NIC");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 356, 199, 27));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DATE OF JOIN");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 393, 195, 27));

        lbl_id.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 0, 51));
        lbl_id.setText("ID");
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 233, 352, -1));

        jLabel31.setBackground(new java.awt.Color(0, 0, 0));
        jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("ID");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 233, 137, 27));
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 310, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1190, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed

        if (txt_fname.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "FIRST NAME IS EMPTY");
        } else {
            String s = "Available";
            String s1 = "%";

        }
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        TransportMain tm = new TransportMain();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(tm).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Btn_Exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Exit3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_Exit3ActionPerformed

    private void table_DriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DriverMouseClicked

        int row = table_Driver.getSelectedRow();

        String id = table_Driver.getValueAt(row, 0).toString();
        String firstName = table_Driver.getValueAt(row, 1).toString();
        String lastName = table_Driver.getValueAt(row, 2).toString();
        Date birthday = (Date) table_Driver.getValueAt(row, 3);
        String nic = table_Driver.getValueAt(row, 4).toString();
        Date doj = (Date) table_Driver.getValueAt(row, 5);
        Date dol = (Date) table_Driver.getValueAt(row, 6);;
        Date lastupdate = (Date) table_Driver.getValueAt(row, 7);
        String mobiled = table_Driver.getValueAt(row, 8).toString();

        try {
            DefaultTableModel model = (DefaultTableModel) table_Driver.getModel();
        } catch (Exception e) {
            System.out.println(e);
        }
        lbl_id.setText(id);
        txt_fname.setText(firstName);
        txt_lname.setText(lastName);
        dateOfBirth.setDate(birthday);
        txt_nic.setText(nic);
        dateOfLeave.setDate(dol);
        dateOfJoin.setDate(doj);
        dateOfLastUpdate.setDate(lastupdate);
        txt_mobileD.setText(mobiled);

    }//GEN-LAST:event_table_DriverMouseClicked

    private void btn_deleteDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteDriverActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "DO YOU REALLY WANT TO DELETE THIS RECORD?");

        if (result == 0) {
            String iddriver = lbl_id.getText();

            String queryForReject = "DELETE FROM driver WHERE Did = '" + iddriver + "' ";
            try {

                pst = (PreparedStatement) con.prepareStatement(queryForReject);
                pst.execute();
                //jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                tableLoad();

                txt_fname.setText("");
                txt_lname.setText("");
                txt_mobileD.setText("");
                txt_nic.setText("");

            } catch (Exception e) {
            }

            tableLoad();

        }
    }//GEN-LAST:event_btn_deleteDriverActionPerformed

    private void btn_updateDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateDriverActionPerformed

        //if (updateResult == 0)
        try {

            String did = lbl_id.getText();
            String firstName = txt_fname.getText();
            String lastName = txt_lname.getText();
            String dob = ((JTextField) dateOfBirth.getDateEditor().getUiComponent()).getText();
            String nic = txt_nic.getText();
            String doj = ((JTextField) dateOfJoin.getDateEditor().getUiComponent()).getText();
            String dol = ((JTextField) dateOfLeave.getDateEditor().getUiComponent()).getText();
            String lastupdate = ((JTextField) dateOfLastUpdate.getDateEditor().getUiComponent()).getText();
            String mobiled = txt_mobileD.getText();

            String sql = "update driver set First_Name='" + firstName + "',Last_Name='" + lastName + "',Birthday='" + dob + "',Nic='" + nic + "',Date_of_Join='" + doj + "',Date_of_leave='" + dol + "',"
                    + "Last_Modified_date='" + lastupdate + "',Mobile_Number='" + mobiled + "' WHERE Did ='" + did + "'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Record Updated");
            //int updateResult = JOptionPane.showConfirmDialog(null, "DO YOU REALLY WANT TO UPDATE ?");
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e);
        }

        tableLoad();
        
    }//GEN-LAST:event_btn_updateDriverActionPerformed

    private void btn_clerDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clerDriverActionPerformed

        txt_fname.setText("");
        txt_lname.setText("");
        txt_mobileD.setText("");
        txt_nic.setText("");
        txt_search.setText("");

    }//GEN-LAST:event_btn_clerDriverActionPerformed

    private void btn_searchDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchDriverActionPerformed

        String DriverName = txt_search.getText();
        String sql = "SELECT * FROM driver WHERE First_Name like '%"+DriverName+"%' or Last_Name like '%"+DriverName+"%' ";
        
        try {
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            table_Driver.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_btn_searchDriverActionPerformed

    private void btn_insertDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertDriverActionPerformed
        //.getText().isEmpty()
        //((JTextField) date_Depature.getDateEditor().getUiComponent()).getText().isEmpty()
        if (txt_fname.getText().isEmpty() || txt_lname.getText().isEmpty() || ((JTextField) dateOfBirth.getDateEditor().getUiComponent()).getText().isEmpty()
                || txt_nic.getText().isEmpty() || ((JTextField) dateOfJoin.getDateEditor().getUiComponent()).getText().isEmpty()
                || ((JTextField) dateOfLastUpdate.getDateEditor().getUiComponent()).getText().isEmpty() || txt_mobileD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAN'T EXIT EMPTY VALUES ");
        } else {
            boolean validnic = ValidationTransportManagement.nicValidation(txt_nic.getText());

            if (validnic) {
                try {
                    pst.setString(5, txt_nic.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(Drivers.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                //JOptionPane.showMessageDialog(null, "DATA INSERTED");\
                JOptionPane.showMessageDialog(null, "INVALID NIC NUMBER");
                //txt_nic.setText("**Enter valid NIC number");
            }

            boolean mnuvalid = ValidationTransportManagement.isMobilePhone(txt_mobileD.getText());
            if (mnuvalid) {

                try {
                    pst.setString(9, txt_mobileD.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(Drivers.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {

                JOptionPane.showMessageDialog(null, "ENTER VALID MOBILE NUMBER ");
            }

            String First_Name = txt_fname.getText();
            String Last_Name = txt_lname.getText();
            String Nic = txt_nic.getText();
            try {

                String sql = "INSERT INTO driver(First_Name,Last_Name,Birthday,Nic,Date_of_Join,Date_of_leave,Last_Modified_date,Mobile_Number) VALUES (?,?,?,?,?,?,?,?)";

                pst = (PreparedStatement) con.prepareStatement(sql);

                pst.setString(1, txt_fname.getText());
                pst.setString(2, txt_lname.getText());
                pst.setString(3, ((JTextField) dateOfBirth.getDateEditor().getUiComponent()).getText());
                pst.setString(4, txt_nic.getText());
                pst.setString(5, ((JTextField) dateOfJoin.getDateEditor().getUiComponent()).getText());
                pst.setString(6, ((JTextField) dateOfLeave.getDateEditor().getUiComponent()).getText());
                pst.setString(7, ((JTextField) dateOfLastUpdate.getDateEditor().getUiComponent()).getText());
                pst.setString(8, txt_mobileD.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null, "DATA INSERTED");
                tableLoad();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println(e);
            }

        }

        //First_Name	Last_Name	Birthday	Nic	Date_of_Join	Date_of_leave	Last_Modified_date
    }//GEN-LAST:event_btn_insertDriverActionPerformed

    private void txt_mobileDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mobileDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mobileDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Exit3;
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton btn_clerDriver;
    private javax.swing.JButton btn_deleteDriver;
    private javax.swing.JButton btn_insertDriver;
    private javax.swing.JButton btn_searchDriver;
    private javax.swing.JButton btn_updateDriver;
    private com.toedter.calendar.JDateChooser dateOfBirth;
    private com.toedter.calendar.JDateChooser dateOfJoin;
    private com.toedter.calendar.JDateChooser dateOfLastUpdate;
    private com.toedter.calendar.JDateChooser dateOfLeave;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_did;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable table_Driver;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mobileD;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
