/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transport_Interface;

import HMS_Database.MyDBConnection;
import com.mysql.jdbc.PreparedStatement;
//import java.sql.Connection;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
import com.mysql.jdbc.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTextField;
import java.util.Date;
import javax.swing.JDesktopPane;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class MyRequest extends javax.swing.JInternalFrame {

    Connection con = null;
    java.sql.PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form MyRequest
     */
    public MyRequest() {
        initComponents();

        con = MyDBConnection.Myconnect();
        //this.setLocationRelativeTo(null);

        tableload23();
    }

    public void tableload23() {
        try {

            String query = "SELECT Reqs_ID,Name,Employee_Number,Department,Mobile_Number,Reporting_Manager,Location,TravelBy,"
                    + "NoOfPasengers,DropPickup,Req_From,Req_To,Depature,Reason FROM add_request_staff ORDER BY Reqs_ID ";
            pst = (PreparedStatement) con.prepareStatement(query);
            rs = pst.executeQuery();

            table_staff.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMenu = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Btn_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_searchName1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_empl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_dept = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_mobilenum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_manager = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_location = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_travelby = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_pasenger = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_pickup = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_from = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_to = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_depatures = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_reasons = new javax.swing.JTextField();
        Btn_Search = new javax.swing.JButton();
        Btn_Update = new javax.swing.JButton();
        Btn_CLEAR = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        lbl_reqId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_staff = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txt_SearchByName = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Transport_Images/MenuBar_Back_Main_Transport.jpg"))); // NOI18N
        jLabel14.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel14.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel14.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 204, 0));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 284, -1));

        Btn_Exit.setBackground(new java.awt.Color(255, 51, 51));
        Btn_Exit.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Exit.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Exit.setText("Exit");
        Btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 402, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 149, 27));
        jPanel1.add(txt_searchName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, 27));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMP_NO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 149, 27));
        jPanel1.add(txt_empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 200, 27));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEPARTMENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 199, 27));

        txt_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deptActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 200, 27));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MOBILE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 199, 27));
        jPanel1.add(txt_mobilenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 200, 27));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MANAGER");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 188, 27));
        jPanel1.add(txt_manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 200, 27));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LOCATION");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 188, 27));
        jPanel1.add(txt_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 200, 27));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TRAVEL");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 149, 27));

        txt_travelby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_travelbyActionPerformed(evt);
            }
        });
        jPanel1.add(txt_travelby, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 200, 27));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PASENGER");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 199, 27));
        jPanel1.add(txt_pasenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 200, 27));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DROP / PICKUP");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 199, 27));
        jPanel1.add(txt_pickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 200, 27));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("FROM");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 190, 27));
        jPanel1.add(txt_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 320, 27));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 190, 27));
        jPanel1.add(txt_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 320, 27));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DEPATURE");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 190, 27));
        jPanel1.add(txt_depatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 320, 27));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("REASON");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 190, 27));

        txt_reasons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_reasonsActionPerformed(evt);
            }
        });
        jPanel1.add(txt_reasons, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 320, 27));

        Btn_Search.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Search.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Search.setForeground(new java.awt.Color(255, 255, 0));
        Btn_Search.setText("SEARCH");
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 692, 32));

        Btn_Update.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Update.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Update.setForeground(new java.awt.Color(255, 255, 0));
        Btn_Update.setText("UPDATE");
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 692, 32));

        Btn_CLEAR.setBackground(new java.awt.Color(0, 0, 0));
        Btn_CLEAR.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_CLEAR.setForeground(new java.awt.Color(255, 255, 0));
        Btn_CLEAR.setText("CLEAR");
        Btn_CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CLEARActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 692, 32));

        Btn_Delete.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Delete.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Delete.setForeground(new java.awt.Color(255, 255, 0));
        Btn_Delete.setText("DELETE");
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 692, 32));

        jLabel19.setBackground(new java.awt.Color(255, 0, 0));
        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("SEARCH BY NAME");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 240, 27));

        lbl_reqId.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lbl_reqId.setForeground(new java.awt.Color(204, 0, 0));
        lbl_reqId.setText("ID");
        jPanel1.add(lbl_reqId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 200, 33));

        table_staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16"
            }
        ));
        table_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_staffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_staff);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1190, 130));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("SEARCH BY REQUEST ID");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 199, 27));
        jPanel1.add(txt_SearchByName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 312, 440, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TransportMain tm = new TransportMain();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(tm).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_ExitActionPerformed

    private void txt_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deptActionPerformed

    private void txt_travelbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_travelbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_travelbyActionPerformed

    private void txt_reasonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_reasonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_reasonsActionPerformed

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed

        String searchName = txt_SearchByName.getText();
        String sql = "SELECT * FROM add_request_staff WHERE Name like '%"+searchName+"%'";
        
        try {
            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            table_staff.setModel(DbUtils.resultSetToTableModel(rs));
                    
                 
            
        } 
        catch (Exception e)
        {
            
            JOptionPane.showMessageDialog(null, e);
        }
        

    }//GEN-LAST:event_Btn_SearchActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed

        int resultTest = JOptionPane.showConfirmDialog(rootPane, "DO YOU WANT TO UPDATE THIS RECOED !");

        if (resultTest == 0) {
            String reqIds = lbl_reqId.getText();
            String names = txt_searchName1.getText();
            String empNos = txt_empl.getText();
            String dept = txt_dept.getText();

            String mobilenum123 = txt_mobilenum.getText();
            String manager = txt_manager.getText();
            String location = txt_location.getText();

            String travelby = txt_travelby.getText();
            String pasenger = txt_pasenger.getText();
            String dropPickup = txt_pickup.getText();
            String froms = txt_from.getText();
            String tos = txt_to.getText();
            String depatures = txt_depatures.getText();
            String reason = txt_reasons.getText();

            //
            String sqlUpdate = " UPDATE add_request_staff SET  Name = '" + names + "', Employee_Number = '" + empNos + "', Department = '" + dept + "', Mobile_Number = '" + mobilenum123 + "',"
                    + " Reporting_Manager = '" + manager + "' ,Location ='" + location + "',TravelBy = '" + travelby + "',NoOfPasengers = '" + pasenger + "',"
                    + "DropPickup='" + dropPickup + "',Req_From='" + froms + "',Req_To='+tos+',Depature='" + depatures + "',Reason='" + reason + "' WHERE Reqs_ID = '" + reqIds + "'";

            try {

                pst = (PreparedStatement) con.prepareStatement(sqlUpdate);

                pst.executeUpdate();

                tableload23();

            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void Btn_CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CLEARActionPerformed
        txt_searchName1.setText("");
        txt_empl.setText("");
        txt_dept.setText("");
        txt_mobilenum.setText("");
        txt_manager.setText("");
        txt_location.setText("");
        txt_travelby.setText("");
        txt_pasenger.setText("");
        txt_pickup.setText("");
        txt_from.setText("");
        txt_to.setText("");
        txt_depatures.setText("");
        txt_reasons.setText("");
        txt_SearchByName.setText("");
    }//GEN-LAST:event_Btn_CLEARActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed

         int result = JOptionPane.showConfirmDialog(null, "DO YOU REALLY WANT TO DELETE THIS RECORD?");

        if (result == 0) {
            String idVehicle = lbl_reqId.getText();

            String queryForReject = "DELETE FROM add_request_staff WHERE Reqs_ID = '" + idVehicle + "' ";
            try {

                pst = (com.mysql.jdbc.PreparedStatement) con.prepareStatement(queryForReject);
                pst.execute();
                txt_searchName1.setText("");
        txt_empl.setText("");
        txt_dept.setText("");
        txt_mobilenum.setText("");
        txt_manager.setText("");
        txt_location.setText("");
        txt_travelby.setText("");
        txt_pasenger.setText("");
        txt_pickup.setText("");
        txt_from.setText("");
        txt_to.setText("");
        txt_depatures.setText("");
        txt_reasons.setText("");
        txt_SearchByName.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

            tableload23();

        }
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void table_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_staffMouseClicked
        // TODO add your handling code here:
        int row = table_staff.getSelectedRow();

        String id = table_staff.getValueAt(row, 0).toString();
        String name = table_staff.getValueAt(row, 1).toString();
        String empl = table_staff.getValueAt(row, 2).toString();
        String dept = table_staff.getValueAt(row, 3).toString();
        String mobi = table_staff.getValueAt(row, 4).toString();
        String manager = table_staff.getValueAt(row, 5).toString();
        String location = table_staff.getValueAt(row, 6).toString();
        String travel = table_staff.getValueAt(row, 7).toString();
        String pasenger = table_staff.getValueAt(row, 8).toString();
        String dropPickup = table_staff.getValueAt(row, 9).toString();
        String from = table_staff.getValueAt(row, 10).toString();
        String to = table_staff.getValueAt(row, 11).toString();
        String depature = table_staff.getValueAt(row, 12).toString();
        String reason = table_staff.getValueAt(row, 13).toString();

        lbl_reqId.setText(id);
        txt_searchName1.setText(name);
        txt_empl.setText(empl);
        txt_dept.setText(dept);
        txt_mobilenum.setText(mobi);
        txt_manager.setText(manager);
        txt_location.setText(location);
        txt_travelby.setText(travel);
        txt_pasenger.setText(pasenger);
        txt_pickup.setText(dropPickup);
        txt_from.setText(from);
        txt_to.setText(to);
        txt_depatures.setText(depature);
        txt_reasons.setText(reason);
    }//GEN-LAST:event_table_staffMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CLEAR;
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JButton Btn_Exit;
    private javax.swing.JButton Btn_Search;
    private javax.swing.JButton Btn_Update;
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_reqId;
    private javax.swing.JTable table_staff;
    private javax.swing.JTextField txt_SearchByName;
    private javax.swing.JTextField txt_depatures;
    private javax.swing.JTextField txt_dept;
    private javax.swing.JTextField txt_empl;
    private javax.swing.JTextField txt_from;
    private javax.swing.JTextField txt_location;
    private javax.swing.JTextField txt_manager;
    private javax.swing.JTextField txt_mobilenum;
    private javax.swing.JTextField txt_pasenger;
    private javax.swing.JTextField txt_pickup;
    private javax.swing.JTextField txt_reasons;
    private javax.swing.JTextField txt_searchName1;
    private javax.swing.JTextField txt_to;
    private javax.swing.JTextField txt_travelby;
    // End of variables declaration//GEN-END:variables
}
