/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transport_Interface;

import HMS_Database.MyDBConnection;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.JTextField;
import javax.swing.JTextField;
import java.util.Date;
import javax.swing.JDesktopPane;

/**
 *
 * @author Prabas Gayadeeptha
 */
public class PendingRequest extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form PendingRequest
     */
    public PendingRequest() {
        initComponents();
        con = MyDBConnection.Myconnect();

        //this.setLocationRelativeTo(null);
        tableload();
    }

    public void tableload() {
        try {

            String query = " SELECT Reqg_ID,Name,RoomNumber,Location,TravelBy,NoOfPasengers,DropPickup,Req_From,Req_To,Depature FROM add_request_guest ORDER BY Reqg_ID ";
            pst = (PreparedStatement) con.prepareStatement(query);
            rs = pst.executeQuery();

            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMenu = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Btn_Back_Pending = new javax.swing.JButton();
        Btn_Approve_Pending = new javax.swing.JButton();
        Btn_Search = new javax.swing.JButton();
        Btn_Reject_Pending = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_searchName = new javax.swing.JTextField();
        txt_searchDate = new javax.swing.JTextField();
        txt_searchRoom = new javax.swing.JTextField();
        txt_searchLocation = new javax.swing.JTextField();
        Btn_Exit_Pending = new javax.swing.JButton();
        Btn_Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1200, 680));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlMenu.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Transport_Images/MenuBar_Back_Main_Transport.jpg"))); // NOI18N
        jLabel14.setMaximumSize(new java.awt.Dimension(1190, 75));
        jLabel14.setMinimumSize(new java.awt.Dimension(1190, 75));
        jLabel14.setPreferredSize(new java.awt.Dimension(1190, 75));
        PnlMenu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Back_Pending.setBackground(new java.awt.Color(255, 153, 0));
        Btn_Back_Pending.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Back_Pending.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Back_Pending.setText("BACK");
        Btn_Back_Pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Back_PendingActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Back_Pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 123, 158, -1));

        Btn_Approve_Pending.setBackground(new java.awt.Color(0, 204, 0));
        Btn_Approve_Pending.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Approve_Pending.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Approve_Pending.setText("APPROVE");
        Btn_Approve_Pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Approve_PendingActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Approve_Pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 11, 158, -1));

        Btn_Search.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Search.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Search.setForeground(new java.awt.Color(255, 255, 0));
        Btn_Search.setText("SEARCH");
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 158, 32));

        Btn_Reject_Pending.setBackground(new java.awt.Color(0, 204, 0));
        Btn_Reject_Pending.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Reject_Pending.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Reject_Pending.setText("REJECT");
        Btn_Reject_Pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reject_PendingActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Reject_Pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 66, 158, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEARCH BY NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 149, 27));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SEARCH BY ROOM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 149, 27));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEARCH BY DATE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 149, 27));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEARCH  BY REQUEST ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 199, 27));
        jPanel1.add(txt_searchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 13, 352, 27));
        jPanel1.add(txt_searchDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 50, 352, 27));

        txt_searchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchRoomActionPerformed(evt);
            }
        });
        jPanel1.add(txt_searchRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 85, 352, 27));
        jPanel1.add(txt_searchLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 127, 352, 27));

        Btn_Exit_Pending.setBackground(new java.awt.Color(255, 51, 51));
        Btn_Exit_Pending.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Exit_Pending.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Exit_Pending.setText("Exit");
        Btn_Exit_Pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Exit_PendingActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Exit_Pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 189, 158, -1));

        Btn_Clear.setBackground(new java.awt.Color(0, 0, 0));
        Btn_Clear.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Btn_Clear.setForeground(new java.awt.Color(255, 255, 0));
        Btn_Clear.setText("CLEAR");
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 187, 158, 32));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 70, 1190, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Back_PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Back_PendingActionPerformed

        TransportMain tm = new TransportMain();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(tm).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_Back_PendingActionPerformed

    private void Btn_Approve_PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Approve_PendingActionPerformed

        int result2 = JOptionPane.showConfirmDialog(null, "APPROVE REQUEST?");

    }//GEN-LAST:event_Btn_Approve_PendingActionPerformed

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed

        String name1 = txt_searchName.getText();
        String date = txt_searchName.getText();
        String room = txt_searchName.getText();
        String reqg = txt_searchName.getText();

        String querySearch = "SELECT * FROM add_request_guest WHERE Name LIKE '%" + name1 + "%' OR Depature LIKE '%" + date + "%'  OR RoomNumber LIKE '%" + room + "%' OR Reqg_ID LIKE '" + reqg + "' ";

        try {

            pst = (PreparedStatement) con.prepareStatement(querySearch);
            // pst = (PreparedStatement) con.prepareStatement(querySearch2);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {

            System.out.println("exception " + e);
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_Btn_SearchActionPerformed

    private void Btn_Reject_PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reject_PendingActionPerformed

        int result = JOptionPane.showConfirmDialog(null, "DO YOU REALLY WANT TO REJECT THIS REQUEST?");

        if (result == 0) {
            String reqg = txt_searchLocation.getText();

            String queryForReject = "DELETE FROM add_request_guest WHERE Reqg_ID = '" + reqg + "' ";
            try {

                pst = (PreparedStatement) con.prepareStatement(queryForReject);
                pst.execute();
                //jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                tableload();

                txt_searchName.setText("");
                txt_searchDate.setText("");
                txt_searchRoom.setText("");
                txt_searchLocation.setText("");

            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_Btn_Reject_PendingActionPerformed

    private void txt_searchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchRoomActionPerformed

    private void Btn_Exit_PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Exit_PendingActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_Exit_PendingActionPerformed

    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed

        txt_searchName.setText("");
        txt_searchDate.setText("");
        txt_searchRoom.setText("");
        txt_searchLocation.setText("");
    }//GEN-LAST:event_Btn_ClearActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        String name = jTable2.getValueAt(row, 1).toString();
        String date = jTable2.getValueAt(row, 9).toString();
        String room = jTable2.getValueAt(row, 2).toString();
        String location = jTable2.getValueAt(row, 0).toString();

        txt_searchName.setText(name);
        txt_searchDate.setText(date);
        txt_searchRoom.setText(room);
        txt_searchLocation.setText(location);
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Approve_Pending;
    private javax.swing.JButton Btn_Back_Pending;
    private javax.swing.JButton Btn_Clear;
    private javax.swing.JButton Btn_Exit_Pending;
    private javax.swing.JButton Btn_Reject_Pending;
    private javax.swing.JButton Btn_Search;
    private javax.swing.JPanel PnlMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_searchDate;
    private javax.swing.JTextField txt_searchLocation;
    private javax.swing.JTextField txt_searchName;
    private javax.swing.JTextField txt_searchRoom;
    // End of variables declaration//GEN-END:variables
}
